### ISSUE TITLE
How to read hyperlinks from XLSX using RubyXL

### ISSUE THREAD

**Issue by kinkou** [weshatheleopard/rubyXL#115]
I was pretty much surprised to find out that's there's no simple way to read hyperlinks from a XLSX file parsed by RubyXL (or is there?)

Obviously, one would expect expect something like 

```
workbook[0][2][3].href
```

but further exploration showed that the only method that I could find to reveal hyperlinks,

```
workbook[0].hyperlinks
```

returned an empty array. I continued my investigation and figured that some of the hyperlinks from my document can be found in XML returned by

```
workbook.worksheet_rels
```

and the output is like this:

```
{
    "sheet1.xml.rels" =>
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>
         <Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">
         <Relationship Id=\"rId3\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink\" Target=\"http://www.domain.com/action1/action2\" TargetMode=\"External\"/>
         ...
}
```

It does contain some of the links from my document, but unfortunately, not all of them.

Can you guys please give some guidance on how to find the hyperlinks?

Thank you.

PS Here's the [file](http://yadi.sk/d/eE2psYx2R3Y4S) that I used for testing, it was created by Excel for Mac 2011 v. 14.0.0

Also,

```
--- > RUBY_VERSION
= "2.0.0"
--- > RUBY_PLATFORM
= "x86_64-darwin13.0.0"
```

with the latest version of the gem.

**Comment by matpowel** [comment]
@weshatheleopard is that branch closed? I can't find it anymore. Was it merged into master?

**Comment by weshatheleopard** [comment]
@matpowel: Yes, it has been merged into main long time ago.

**Comment by matpowel** [comment]
@weshatheleopard ok, hyperlinks were not working at all for me though so I had to switch to use the Roo ::Excelx library, from memory there was no .hyperlinks method at all that we could find?

**Comment by weshatheleopard** [comment]
```
require 'rubyXL'
 doc = RubyXL::Parser.parse('test/input/test.xlsx')
 doc.worksheets[0].hyperlinks
```

**Comment by weshatheleopard** [comment]
@matpowel: see the sample code above.

**Comment by karthik-panchap** [comment]
@weshatheleopard  My usecase / workflow requires inspecting specific cell for a hyperlink.  Given a cell what is the most elegant way to obtain the contained hyperlink?

**Comment by weshatheleopard** [comment]
@karthik-panchap : can you give me a minimal sample spreadsheet which has what you want to obtain from it?

**Comment by karthik-panchap** [comment]
@weshatheleopard  Sure, here is a quick example.  
[sample.xlsx](https://github.com/weshatheleopard/rubyXL/files/163902/sample.xlsx)

Workflow requires getting link from specific cells in the workbook ex: for the apple workbook[0][1][2].

**Comment by weshatheleopard** [comment]
@karthik-panchap:

```
require 'rubyXL' 
doc = RubyXL::Parser.parse('sample.xlsx')
sheet = doc[0]

sheet.sheet_data.rows.each { |row|
  next if row.nil?
  row.cells.each { |cell|
    next if cell.nil?
    hl = sheet.hyperlinks.find{ |hl| hl.ref == cell.r }
    next if hl.nil?
    ext_link = sheet.relationship_container.find_by_rid(hl.r_id)
    next if ext_link.nil?
    
    puts "Cell at #{cell.r.to_s} -- links to #{ext_link.target}" 
  }
}
```

**Comment by joshuapinter** [comment]
I just wanted to share our implementation because we ran into situations where the `relationship_container.target` included half of the URL and the `hyperlink.location` included the other half. 

```ruby
hyperlink = worksheet.hyperlinks.find{ |hyperlink| hyperlink.ref == cell.r }

raise "Could not find hyperlink for #{ cell.r }" if hyperlink.nil?

relationship = worksheet.relationship_container.find_by_rid( hyperlink.r_id )

raise "Could not find relationship for #{ cell.r }" if relationship.nil?

"#{ relationship.target }#{ hyperlink.location }"
```
