### ISSUE TITLE
Saved xlsx can't open if created via RubyXL::Workbook.new.

### ISSUE THREAD

**Issue by xpol** [weshatheleopard/rubyXL#158]
``` Ruby
require 'rubygems'
require 'rubyXL'

wb = RubyXL::Workbook.new
wb.write('simple.xlsx')
```

The `simple.xlsx` would not open by Numbers (not test with MS Excel).

**Comment by villesundberg** [comment]
I ran into this today. The root cause is that rubyXL writes a reference to `sharedStrings.xml`, but not the actual file. Manually deleting the reference

```
<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>
```

fixes the problem.

This appears to be a regression of #44.

Numbers is the Excel-compatible spreadsheet program included in OS X.

**Comment by kiramclean** [comment]
Any fix for this? Excel sucks I don't want to have to download it to use this gem.
