### ISSUE TITLE
Unknown child node [mc:AlternateContent] for element [oleObjects]

### ISSUE THREAD

**Issue by ngiger** [weshatheleopard/rubyXL#163]
We were able to use previous versions of the file found under "Excel-version of authorized packaging\* "  on
https://www.swissmedic.ch/arzneimittel/00156/00221/00222/00230/index.html?lang=en

Since it last update we are unable to open it. We could reduce it to the following code

require 'rubyXL'
workbook = RubyXL::Parser.parse('Zugelassene_Packungen_301114.xlsx') do |row| puts row.inspect; break; end

Even working with the latest head (including commit https://github.com/weshatheleopard/rubyXL/commit/64460d19510f87bc852815dbb530fde4b3bbad04 Issue #82: more unexpected nodes. ) did not fix the problem.

**Comment by achyuthgit** [comment]
I am facing same issue and using 3.3.29 version, how do i resolve ?

**Comment by weshatheleopard** [comment]
@achyuthgit please give me the file that is causing this problem for you.

**Comment by achyuthgit** [comment]
[RestAPI - Copy.xlsx](https://github.com/weshatheleopard/rubyXL/files/2316943/RestAPI.-.Copy.xlsx)

attaching the file which is causing the issue

**Comment by achyuthgit** [comment]
let me know if you need more details

**Comment by achyuthgit** [comment]
@weshatheleopard any help here would unblock me
