### ISSUE TITLE
How we can add formats(i.e integer,float,string,text..etc) to cell or coloumns

### ISSUE THREAD

**Issue by shivareddy547** [weshatheleopard/rubyXL#168]
Hi,

I Created Xlsx file which is have 10 columns and all values are text format.
But i need some columns are integers,strings,floats,dates.

How i can do it..?
Please can you help me..?

Thanks in Advance.

Thanks
Shivareddy.A

**Comment by liudangyi** [comment]
:+1:

**Comment by weshatheleopard** [comment]
Added convenience method in 3.3.10.
