### ISSUE TITLE
get_table stops including column data after an empty cell in the column

### ISSUE THREAD

**Issue by paul-palmer** [weshatheleopard/rubyXL#171]
If you use get_table to parse a spreadsheet like:

a      b      c
1      2      3
        4      5
6      7      8

The table data will not include '6'.

**Comment by weshatheleopard** [comment]
Unable to reproduce.

```
 > doc.worksheets[0].extract_data
 => [["a", "b", "c"], [1, 2, 3], [4, 5], [6, 7, 8]]
```
