### ISSUE TITLE
is_bolded

### ISSUE THREAD

**Issue by lionelperrin** [weshatheleopard/rubyXL#179]
The test I did using ruby 2.1.5p273, nokogiri 1.6.6.2, rubyXL(3.3.4) shown that Cell#is_bolded always return 'nil'.
When <b/> attribute is not present, Font#b is nil and then Font#is_bold (definied as b && b.val) returns nil.
When <b/> attribute is present, Font#b is a BooleanNode, but its val is nil. This cause Font#is_bold to return nil.

**Comment by weshatheleopard** [comment]
Fixed.

**Comment by weshatheleopard** [comment]
@RKushnir : fixed that.

**Comment by RKushnir** [comment]
@weshatheleopard Thank you, that was really fast!
