### ISSUE TITLE
Why is it so slow

### ISSUE THREAD

**Issue by westonganger** [weshatheleopard/rubyXL#185]
I like that this gem is more recent and works with XLSX and has better documentation

But why is it so ridiculously slow compared to 'spreadsheet' ?

**Comment by weshatheleopard** [comment]
@westonganger: I have no idea what `spreadsheet` is, but for one guess I can give you is because whatever that gem is, it, unlike `rubyXL`, does not support the full XLSX DOM model.

**Comment by westonganger** [comment]
spreadsheet is the biggest ruby [spreadsheet gem](https://github.com/zdavatz/spreadsheet). I didnt do any benchmarks but just to let you know that in the time it took to do 2 lines in rubyXL, spreadsheet did 430.

It may be advantageous to look at their source code for any speed improvements

**Comment by weshatheleopard** [comment]
> time it took to do 2 lines in rubyXL, spreadsheet did 430.

`rubyXL` works with `xlsx` files (open OOXML format: https://en.wikipedia.org/wiki/Office_Open_XML). `spreadsheet` works with `xls` files (proprietary MS Excel format: http://www.digitalpreservation.gov/formats/digformatspecs/Excel97-2007BinaryFileFormat%28xls%29Specification.pdf). *Surprise surprise*, binary stuff works faster than XML! Next time, please ensure you compare apples to oranges.
