### ISSUE TITLE
Issue with conditional formatting

### ISSUE THREAD

**Issue by PeJack** [weshatheleopard/rubyXL#189]
I have xlsx. file with 3 columns, which has conditional formatting. In each column - its rule.
But after parsing file through gem and save it they response  last condition, removes the other.
In rails console I also see only one condition.

**Comment by kisara-icy** [comment]
Conditional formatting is saved only one case currently.
But I found that following change can save multiple case.

lib/rubyXL/objects/worksheet.rb
    define_child_node(RubyXL::ConditionalFormatting)
                                                                                    vvvv
    define_child_node(RubyXL::ConditionalFormatting, :collection => true)

I want to reflect the modification .

Thanks.

**Comment by weshatheleopard** [comment]
Fixed in 3.3.9
