### ISSUE TITLE
change_text_wrap (and other) does not work with existing book

### ISSUE THREAD

**Issue by gwww** [weshatheleopard/rubyXL#191]
Open an existing and empty .xlsx file using RubyXL.
Add cell 0,0, "Hello"
Write book.
Open book with excel. Looks fine. Cell A1 has "Hello".
In Excel save file.
Using RubyXL open book again....
```
b=RubyXL::Parser.parse "Test.xlsx"
s=b['Sheet1']
s[0][0] returns: #<RubyXL::Cell(0,0): "0", datatype = s, style_index = >
```
Note that style_index is blank. This causes change_text_wrap (and similar methods) to fail.

Excel is 2010 on Windows.

**Comment by gwww** [comment]
As I don't know the code well enough, a specific fix that appears to work is to change the first line of modify_alignment in convenience_methods.rb (line 151) from:
```
xf = cell_xfs[style_index].dup
```
to
```
xf = cell_xfs[style_index || 0].dup
```
I believe that a more general fix is required. Not sure what that is.

**Comment by weshatheleopard** [comment]
I believe this has been fixed during one of the previous refactorings. At least I cannot reproduce it anymore. Please try the latest gem version and report if you are still having this problem.

**Comment by bsutherland** [comment]
I'm having this issue with 3.3.16 and the attached Excel file:

[lil.xlsx](https://github.com/weshatheleopard/rubyXL/files/140283/lil.xlsx)

I'm working around it like this:

```
# To work around a bug in RubyXL
cell.style_index ||= 0
# This is necessary to preserve line breaks.
# https://github.com/weshatheleopard/rubyXL/issues/209
cell.change_text_wrap(true)
```
