### ISSUE TITLE
Row stops including data after empty cell (similar to issue #171)

### ISSUE THREAD

**Issue by heycait** [weshatheleopard/rubyXL#194]
Similar to issue #171 except I have data that looks like this:

1 2 3 4 5 6 7
a b c d e f
g h i j k l m
n o p q r s
t u v q x y

I have headers that extend all the way to 7, but the data in each row has an empty cell there. The data that comes back using extract_data appears to just stop after it sees an empty cell followed by other empty cells. Is there a way to have it extend as far as the first row's data?

**Comment by weshatheleopard** [comment]
Unable to reproduce.

```
> doc.worksheets[0].extract_data
 => [[1, 2, 3, 4, 5, 6, 7], ["a", "b", "c", "d", "e", "f"], ["g", "h", "i", "j", "k", "l", "m"], ["n", "o", "p", "q", "r", "s"], ["t", "u", "v", "q", "x", "y"]]
```

Please provide a sample XLSX file.

**Comment by heycait** [comment]
Here's a snippet of the data I'm using:
![image](https://cloud.githubusercontent.com/assets/7475663/9049339/e50fea6e-39f5-11e5-831e-91d6cc876c7a.png)


Calling extract_data on this file gives me the following (the data ends at 1 in each row):
```
[["factual_id", "name", "address", "address_extended", "po_box", "locality", "region", "post_town", "admin_region", "postcode", "country", "tel", "fax", "latitude", "longitude", "neighborhood", "website", "email", "category_ids", "category_labels", "status", "chain_name", "chain_id"], ["b716c681-ad67-4c9c-aab4-7f5fb39e3e11", "Bt Newby Heating and Air Conditioning", "5601 Jessup Meadows Dr", nil, nil, "North Chesterfield", "VA", nil, nil, 23234, "us", "(804) 241-6736", nil, 37.441295, -77.501949, nil, nil, "btnewbybuilder@tds.net", "[\"247\"]", "[\"Services and Supplies\",\"Home Improvement\",\"Heating, Ventilating and Air Conditioning\"]", 1], ["07bc1fc4-084f-4ec0-a161-1a363857071b", "Blasus", "8120 Edgewater Ln", nil, nil, "Burton", "TX", nil, nil, 77835, "us", "(979) 289-5031", nil, 30.279511, -96.638227, nil, nil, nil, "[\"177\"]", "[\"Services and Supplies\"]", 1], ["731b17c0-1e18-012f-0643-0030487f54d8", "Palm Beach Radio Broadcasting", "901 Northpoint Pkwy", "Ste 303", nil, "West Palm Beach", "FL", nil, nil, 33407, "us", "(561) 471-3600", nil, 26.762625, -80.094699, nil, nil, nil, "[\"215\"]", "[\"Services and Supplies\",\"Entertainment\",\"Media\"]", 1]]
```

**Comment by weshatheleopard** [comment]
Please provide the actual xlsx file.

**Comment by weshatheleopard** [comment]
> the data ends at 1 in each row

But, according to your picture, there is no data after 1 in each row. What do you expect to be there?

**Comment by heycait** [comment]
I am unable to do so here as it's unsupported. Trying to upload the data to Google docs now. 

I just need it to tell me it's an empty row under that heading. I've by-passed this issue on my side but thought it'd be nice if the gem did it too.

**Comment by heycait** [comment]
Here's the link to view the data
https://docs.google.com/spreadsheets/d/1Za0QNXweGPrGgDT5oNaUzvB1qAKaAbNQedMebaWmcXc/edit?usp=sharing

**Comment by weshatheleopard** [comment]
Relying on convenience methods such as `extract_data` and `get_table` is highly not recommended, and they might eventually be removed from the gem altogether. Instead, you should access the data you want through a lower level interface, like ```sheet[row][col].value``` — not only you will be able to bypass the unnecessary memory reallocation, but you also will be able to manipulate data in exactly the way you want.

**Comment by heycait** [comment]
Oh ok thanks for the advice. Just thought that'd be best to use since I needed to check all the cells for comparison and didn't want it to iterate multiple times.
