### ISSUE TITLE
incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)

### ISSUE THREAD

**Issue by ryanmark** [weshatheleopard/rubyXL#195]
RubyXL crashes when trying to read certain cells with weirdly encoded contents. I'll attach a file that will recreate this issue:

```ruby
require 'rubyXL'
xls = RubyXL::Parser.parse('./test.xlsx')
xls.worksheets.first.extract_data
/stuff/.bundle/gems/rubyXL-3.3.10/lib/rubyXL/objects/text.rb:27:in `gsub': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
```

Here is the file:
https://dl.dropboxusercontent.com/u/29668/test.xlsx

I will make a branch and pull request that simply catches this exception passes the text unescaped.

**Comment by weshatheleopard** [comment]
The biggest thing I hate in this world is software developers that don't fix the *actual* problem, but simply suppress its manifestation — "sweep their trash under the rug".
