### ISSUE TITLE
Change cell datatype

### ISSUE THREAD

**Issue by vmamaev** [weshatheleopard/rubyXL#204]
How to change cell datatype?

I want to change Date format to String...

**Comment by weshatheleopard** [comment]
I don't see what kind of difficulty you are having.

```
workbook = RubyXL::Parser.parse("in.xlsx")
cell = workbook[0][0][0]
my_date = cell.value
cell.change_contents(my_date.to_s)
workbook.save "out.xlsx"
```
so you don't need to change anything explicitly.

In order you want to do a more specific manipulations, you can always do `cell.datatype = RubyXL::DataType::RAW_STRING` or the like.
