### ISSUE TITLE
Incorrect delete_row 

### ISSUE THREAD

**Issue by vmamaev** [weshatheleopard/rubyXL#207]
I have a following xlsx file:
![delete_row](https://cloud.githubusercontent.com/assets/1883631/10715749/9f63a978-7b32-11e5-8c57-9a2956fa611a.png)

When I try to delete empty row with number 8 (or index 7) I received "undefined method `cells' for nil:NilClass".

code in model: 
```
def delete_xlsx_row(row_id)
    w_book  = work_book
    w_sheet = w_book[0]
    w_sheet.delete_row(row_id.to_i)
    w_book.write(source.path)
    ....
end
```

How I can delete empty rows (№5,6,7,8,9)?

**Comment by dunn** [comment]
Just ran into this also.  Looks like the issue is that it's trying to shift the row of the _cells_ of each row below the deleted one, but failing since empty rows are `nil`: https://github.com/weshatheleopard/rubyXL/blob/master/lib/rubyXL/worksheet.rb#L118

**Comment by weshatheleopard** [comment]
@dunn, can you please test the current `master`?

**Comment by dunn** [comment]
I believe the problem is still there.

Here's my test script:
```ruby
require "rubyXL"

book = (RubyXL::Parser.parse "#{ENV["HOME"]}/test/rubyxl/test.xlsx")

book.each do |sheet|
  sheet.each_with_index do |row, i|
    sheet.delete_row(i) if row.nil?
  end

  sheet.each do |row|
    row.cells.each do |cell|
      puts cell.inspect
    end
  end
end
```
And `test.xlsx` is just this:
![screen shot 2015-11-02 at 12 30 11 pm](https://cloud.githubusercontent.com/assets/985416/10893431/91c2d754-815d-11e5-9c7f-67c3a5e8c72b.png)

Expected output of `bundle exec ruby rows.rb`:
```
nil
#<RubyXL::Cell(1,1): "0", datatype="s", style_index=nil>
nil
#<RubyXL::Cell(2,1): "1", datatype="s", style_index=nil>
```

Actual:
```
rows.rb:11:in `block (2 levels) in <main>': undefined method `cells' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/rubyXL-874b140900dd/lib/rubyXL/worksheet.rb:23:in `block in each'
        from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/rubyXL-874b140900dd/lib/rubyXL/worksheet.rb:23:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/rubyXL-874b140900dd/lib/rubyXL/worksheet.rb:23:in `each'
        from rows.rb:10:in `block in <main>'
        from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/rubyXL-874b140900dd/lib/rubyXL/convenience_methods.rb:31:in `block in each'
        from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/rubyXL-874b140900dd/lib/rubyXL/convenience_methods.rb:31:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/rubyXL-874b140900dd/lib/rubyXL/convenience_methods.rb:31:in `each'
        from rows.rb:5:in `<main>'
```

**Comment by weshatheleopard** [comment]
I believe that your problem stems from the fact that you are iterating the same collection you are altering:

```
  sheet.each_with_index do |row, i|
    sheet.delete_row(i) if row.nil?
  end
```

Can you do a simpler test, like deleting a single row?

**Comment by dunn** [comment]
You're right! Changing that block to `sheet.delete_row(0) while sheet.first.nil?` works.

Thanks you!

**Comment by weshatheleopard** [comment]
OK, thanks, will push the gem in a few

**Comment by hiennv0802** [comment]
Hi all, i have some blank rows with border like this:

<img width="966" alt="blank_row" src="https://user-images.githubusercontent.com/8738514/135128729-c7f911e5-b541-4cda-baca-c9e0fe9f3ead.png">

I'm using syntax delete row but not working, could you give me the ideal. Thanks all!

```
worksheet.delete_row(row_number)
```
