### ISSUE TITLE
Can I read value from a worksheet into memory?

### ISSUE THREAD

**Issue by MindaugasBernatavicius** [weshatheleopard/rubyXL#208]
Hi, 

Can I read value from a worksheet into memory? What I would like to to do is get the value of a string in a spreadsheet into memory for manipulation.

I did this:
```
mindaugas@Mindaugas-Lenovo-Y50-70:~/Ruby_Scripts$ ruby 1.rb
#<RubyXL::Cell(1,0): "0", datatype="s", style_index=0>
#<RubyXL::Cell:0x007f5a52ae5d68>
```

My the data that I have in the sheet is
1 | 2 |
A | 4 |

So instead of holding the value A it has "0", but gets the datatype correctly (this is what I think is going on).

Also my code:
```
workbook = RubyXL::Parser.parse("report.xlsx")

worksheet = workbook['Sheet1']

p worksheet.sheet_data[1][0] 	# Returns cell A1 in the worksheet
puts worksheet[0][0]		# Returns cell A1 in the worksheet
```

If I change the data to
1 | 2 |
55 | 4 |

It gets tha value correctly:
```
#<RubyXL::Cell(1,0): "55", datatype="n", style_index=0>
```

**Comment by weshatheleopard** [comment]
I'm not quite sure I'm following your thought, but I think what you wanted is `puts worksheet[0][0].value`

**Comment by MindaugasBernatavicius** [comment]
Thanks, this is what I wanted! Works for strings and for numerics.
