### ISSUE TITLE
Can I enable cell wrapping to have newlines in one cell?

### ISSUE THREAD

**Issue by MindaugasBernatavicius** [weshatheleopard/rubyXL#209]
Hi, 

Refering to this https://github.com/weshatheleopard/rubyXL/issues/29
Newlines can be added, just not sure how can I add wrapping.

Thank you.

**Comment by weshatheleopard** [comment]
`cell.change_text_wrap(true | false)`

**Comment by MindaugasBernatavicius** [comment]
Thanks, can you also tell me how to make the cell be exatly the size of the largest value in the column / row to which it belongs? The behaviour that you get when clicking on the column letter "A" (e.g.) and it expands to match the size of the largest text.

Greatly appreciate your help!

**Comment by weshatheleopard** [comment]
"Эй, двое-из-ларца-одинаковы-с-лица! А вы правда всё-всё за меня делать будете?" :)

**Comment by MindaugasBernatavicius** [comment]
Вы называете меня нашарником? :p ... Please help if you can, new to Ruby and need to automate some report generation :)

**Comment by MindaugasBernatavicius** [comment]
The thing I'm talking about is autofit'ing: http://superuser.com/questions/29265/how-can-i-get-a-cell-in-excel-to-automatically-adjust-its-height-to-fit-the-wrap

**Comment by weshatheleopard** [comment]
Ну а что Вы предлагаете, чтобы я сделал? Написал за Вас простенький цикл, проходящий по колонке и определяющий максимальное число символов в находящихся в них данных `n`, а потом `worksheet.change_column_width(n)`? Это же детский сад.

**Comment by MindaugasBernatavicius** [comment]
Нет, канешо :) Я просто хотел узнать ест ли кокои то метод в rubyXL с помощю которово я мог бы ето сделат... Спосибо :)

**Comment by weshatheleopard** [comment]
Дело в том, что каждый спрашивает: "а почему оно не умеет делать XXX, это же так просто?" Вот только проблема в том, что у каждого спрашивающего XXX своё. Если я каждому буду делать "маленький простенький метод, который делает XXX", то в конце концов получится реализация MS Excel на Ruby. Нет, лучше пусть спрашивающий напишет, и пришлёт pull request. :-b

**Comment by MindaugasBernatavicius** [comment]
У меня небыло даже однои мысли приглосить написать метод дла аутофита :) ... толко узнать есть ли токой уже чтобы не пытатся изобретать велосипед :)

Думаю что решение перемен дизаина плодотворная. Если мой навыки на Руби ывеличибаются может буть я пришлю пул-реквест имено дла аутофита :) ... но не обещаю ;P

**Comment by weshatheleopard** [comment]
> толко узнать есть ли токой уже чтобы не пытатся изобретать велосипед :)

Так я и отвечаю, *почему* его нет. Так же, как нет возможности самому нарисовать диаграмму и т.п. ;)
