### ISSUE TITLE
Writing Dates won't be recognized as date

### ISSUE THREAD

**Issue by wkotzan-avant** [weshatheleopard/rubyXL#210]
I'm trying to output a date. I set the cell datatype like so:

    cell.datatype = RubyXL::DataType::DATE

Excel just won't recognize cells I set as a date in this manner. I've tried setting the cell in a variety of formats

```
#<RubyXL::Cell(2,7): 42339, datatype="d", style_index=0>  # gives me an "open and repair" message
#<RubyXL::Cell(2,7): "42339", datatype="d", style_index=0>
#<RubyXL::Cell(2,7): "3/1/2015", datatype="d", style_index=0> 
```

In every one of these cases, Excel won't display it as a Date. Usually wants to display it as text or a number. What's the proper way to set up a cell to display formatted as a date?

**Comment by weshatheleopard** [comment]
```
c = workbook[0].add_cell(0,0)
c.set_number_format('d-mmm-yy')
c.change_contents(Date.today)
```

What happened to all the people today? Why suddenly everybody is too lazy to spend some time and do your own research?

**Comment by adysson** [comment]
@weshatheleopard 
hi, there is no method `set_number_format()`, how can I set date format to a cell, please?
