### ISSUE TITLE
undefined method 'formula', 'change_contents' for nil:NilClass on blank line

### ISSUE THREAD

**Issue by HEATH3N** [weshatheleopard/rubyXL#211]
I was iterating through rows and changing the contents to "foo" when I unexpectedly got the formula error. I couldn't see anything different about the line but removed the formula argument anyway. The error then changed to "undefined method 'change_contents'"

**Comment by amithekc** [comment]
Hey,
Did you resolve this? I am facing the same issue. No luck yet.

**Comment by HEATH3N** [comment]
Hey,
What I ultimately ended up doing

**Comment by HEATH3N** [comment]
Hey,
What I ultimately ended up doing is calling `.nil?` on the cell and using `.add_cell` to just add an empty string to the cell.
I'm wondering if I should do a pull request to add that as a check automatically. I can't think of why anyone would _want_ a nil value.

**Comment by weshatheleopard** [comment]
The reason why "someone would want a nil value" is space savings.

If you want to add a single cell at ZZ999, you don't want thousands of rows cells created just for it.

When iterating, your code **must** expect that any row in the sheet or any cell in the row may can be `nill`.
