### ISSUE TITLE
[Q] colspan and rowspan

### ISSUE THREAD

**Issue by hiroyuki-sato** [weshatheleopard/rubyXL#213]
Hello I'm newbie rubyXL.

Is it possible to get colspan and rowspan values with rubyXL?
For example,

![](https://gist.githubusercontent.com/hiroyuki-sato/0d2311567356645d36d3/raw/55bbccf403388abf4839599715c5e1e010017837/image.png)

* A1 has colspan 3, E1 too.
* A2 has rowspan 2

Best regards.

**Comment by weshatheleopard** [comment]
These are not "spans". These are merged cells.

```
worksheet = workbook[0]
worksheet.merged_cells
```

(Note that there's also a method: `worksheet.merge_cells` that creates those merged areas. Don't confuse the two.)

**Comment by hiroyuki-sato** [comment]
@weshatheleopard 

Thank you for replying.

It worked!!.

```ruby
merged_cell = worksheet.merged_cells.first
merged_cell.ref.col_range
merged_cell.ref.row_range
```

**Comment by hiennv0802** [comment]
@weshatheleopard @hiroyuki-sato 
Hello, is there any way to merge_rows?
I searched but still can't find any documents.
Thanks!

**Comment by weshatheleopard** [comment]
@hiennv0802 I am not sure what you mean.

**Comment by hiennv0802** [comment]
@weshatheleopard 
Thanks for your replying.
I mean how to merge rows (A2 - A3) like  hiroyuki-sato example:

![image](https://user-images.githubusercontent.com/8738514/125880109-b09340c0-dfe3-4d5c-9219-f6e02d26e526.png)

I'm only know merge cell using syntax: `worksheet.merge_cells(....)` but can't find syntax merge rows.
Maybe the library not supporting it?

**Comment by weshatheleopard** [comment]
What you are showing me **_is_** "merging cells".

**Comment by hiennv0802** [comment]
@weshatheleopard 
Sorry for misunderstand.
I confused between merge cell is only merge columns.
My problem is resolved.
Thanks!
