### ISSUE TITLE
date is not recognized as date by Excel

### ISSUE THREAD

**Issue by adysson** [weshatheleopard/rubyXL#218]
Hi,
when exporting XLSX from Ruby, I'm not able to format cells as date.

I tried to use solution from #210 , but there is no method `set_number_format` in the gem.
I tried to set formula to `d` during a call of `insert_cell`, but only first number of the format is recognized (2015 in 2015-01-01, 1 in 1/1/2015).

Expected behavior:
During export of data from Ruby, I can mark a cell as date format. Afterwards, string `2015-01-01` is recognized as date 2015-01-01 in Excel.

Is that possible to do?

Thanky you!

**Comment by weshatheleopard** [comment]
> I tried to use solution from #210 , but there is no method set_number_format in the gem.

Ummmmm **WHAT**???

```> rake console
irb(main):001:0> require 'rubyXL'
=> true
irb(main):002:0> workbook = RubyXL::Workbook.new
=> <........>
irb(main):003:0> c = workbook[0].add_cell(0,0)
=> #<RubyXL::Cell(0,0): "", datatype="str", style_index=0>
irb(main):004:0> c.set_number_format('d-mmm-yy')
=> 1
irb(main):005:0>
```

**Comment by adysson** [comment]
@weshatheleopard ok, i see. i had version 3.2.6, seems that was the issue. thank you and sorry :)

**Comment by weshatheleopard** [comment]
Yeah, current one is `3.3.17`, so you were a couple years behind.
