### ISSUE TITLE
Excel could not open [file] because some content is unreadable. Do you want to open and repair this workbook?

### ISSUE THREAD

**Issue by jbrass** [weshatheleopard/rubyXL#221]
I have the following basic code for creating a new spreadsheet. 

```
workbook = RubyXL::Workbook.new
worksheet = workbook[0]
row_pointer = 0;
myData.each do |issue|
  column_pointer = 0
  issue.each do | field |
    
    worksheet.add_cell(row_pointer, column_pointer, field)  
    column_pointer = column_pointer+1
  end
  row_pointer = row_pointer+1
end

workbook.write(@options[:output]+'.'+Time.now.to_i.to_s+".xlsx")

```
When I open this file in Excel I am always getting the following error:

![screen shot 2016-03-14 at 6 00 43 pm](https://cloud.githubusercontent.com/assets/125982/13764642/c385cffc-ea0e-11e5-9ba6-0f4837747f73.png)

Ultimately i am able to recover the data - but what could be causing this error? I have used this gem many times for reading files. Thanks!

**Comment by jbrass** [comment]
After i removed a field that was dumping very large values - the error went away. Is there a character limit in excel?

**Comment by weshatheleopard** [comment]
@jbrass: probably your `field` returns `Integer`s and they confuse Excel if they are very large.

Try: `worksheet.add_cell(row_pointer, column_pointer, field.to_s)`

**Comment by jbrass** [comment]
Thanks sounds good.
