### ISSUE TITLE
Waiting for return data to finish displaying takes too long

### ISSUE THREAD

**Issue by abigoroth** [weshatheleopard/rubyXL#225]
i have something like this : 

```
  def self.load_xlsx(file)
    require 'rubyXL'
    workbook = RubyXL::Parser.parse(file)
    sheet = workbook[0]
    sheet[1..-1].each do |s|
        puts s[2].value
      end
    end
```

and i got what i want. but my console freezes and the return data keep flooding my console continuously. I don't understand why is this happening.

**Comment by weshatheleopard** [comment]
`each()` returns the array it has been iterating over, so there's no wonder it returns all the sheets, and that's what you see.

To suppress that in console, do something like:
```
[1,2,3].each do |x| 
  ... do something...
end; nil # return nil as the execution result, not what 'each' returns
```
