### ISSUE TITLE
Clicking dropdown 

### ISSUE THREAD

**Issue by timkellogg** [weshatheleopard/rubyXL#226]
Is it possible to click a dropdown in excel and then read the rows after that?

I could not find it in the documentation. 

Thanks!

**Comment by weshatheleopard** [comment]
I do not understand your question.

**Comment by timkellogg** [comment]
I have an Excel spreadsheet that has a dropdown for states such as Alabama, Alaska, etc.  That dropdown toggles values for other rows.  For example, state spending columns are tracked to which state is selected.  Right now my script reads in those columns but cannot change the state.  Effectively, this means that I must save a new excel spreadsheet for every column.  I'm wondering if the API provides a way to click on the excel dropdown and change the values referenced.

**Comment by weshatheleopard** [comment]
`rubyXL` does not support any interactivity at this moment. It requires an immense amount of work (pretty much, re-implementing entire Excel functionality in ruby) and, given that I do it in my free time, it is unlikely anytime soon.

**Comment by timkellogg** [comment]
I completely understand.  I didn't think this would be the case, I was just interested in wondering if that was a possibility.  Thanks
