### ISSUE TITLE
No such file or directory 2016_04_10_18_37_40_0200/docProps/app.xml

### ISSUE THREAD

**Issue by mo3taz-abdallh** [weshatheleopard/rubyXL#227]
Hello
I have faced the following issue No such file or directory 2016_04_10_18_37_40_0200/docProps/app.xml

Any help?

**Comment by weshatheleopard** [comment]
Please provide the sample file you are having problems with.

**Comment by mo3taz-abdallh** [comment]
here is file
[sheet](https://drive.google.com/open?id=0B5kDn4FzsvwjYm4xUVBZelhabG8)

**Comment by weshatheleopard** [comment]
Are you sure you are using the latest version? Current `RubyXL` version is `3.3.17`.

```
> require 'rubyXL'
 => true
> RubyXL::Parser.parse 'worksheet.xlsx'
 => #<RubyXL::Workbook:0x000000027557e0 ......>

Works just fine.
