### ISSUE TITLE
Header/Footer missing after parsing/writing

### ISSUE THREAD

**Issue by hvolpers** [weshatheleopard/rubyXL#228]
Hi,

I'm using RubyXL to generate reports based on xlsx files. Everything is but, only footer / header seem to be an issue.
I am using a xlsx template with header / footer defined, but after reading and writing it to a new file the footer / header is gone.

Am I missing something?

```ruby
xlsx = RubyXL::Parser.parse("#{Rails.root}/reports/template.xlsx")
xlsx.write("#{Rails.root}/reports/test.xlsx")
```

Thx for any support on this topic.

P.S.: The german Excel version was used to create the template, not sure if that makes any difference.

**Comment by weshatheleopard** [comment]
Can you please provide your `template.xlsx` file so I can investigate?

**Comment by weshatheleopard** [comment]
Fixed version released.

**Comment by hvolpers** [comment]
works, thank you!
