### ISSUE TITLE
How can I set active cell in worksheet view?

### ISSUE THREAD

**Issue by stevefolly** [weshatheleopard/rubyXL#229]
Hi,

How can I set the active cell in a worksheet view?

My scenario is that I'm modifying a 'template' spreadsheet to fill in some data, but I want to set the active cell back to A1 just in case somebody left it somewhere random when they saved the template.

I've got a WorksheetView instance, but can't see how to set it.

Thanks

**Comment by weshatheleopard** [comment]
If we want to make cell `D10` active:

```
doc = RubyXL::Parser.parse('input.xlsx')
worksheet = doc[0]
worksheet.sheet_views.first.selections.clear
worksheet.sheet_views.first.selections <<
  RubyXL::Selection.new(:active_cell => RubyXL::Sqref.new("D10"),
                        :sqref       => RubyXL::Sqref.new("D10"))
doc.save("output.xlsx")
```
