### ISSUE TITLE
It works, but...

### ISSUE THREAD

**Issue by Dysp** [weshatheleopard/rubyXL#238]
I don't know if this is the place to write stuff like this. I am quite new to Ruby and I've been trying to do some TDD.
I am writing a test and loading a file; my tests succeed and I get back what I expect. But on top of that, I am getting a huge list of exceptions from RubyXL. Am I doing something wrong?

https://gist.github.com/Dysp/7f375bef79a2b1779307d62676b06545

Let me know if you need anything else.

**Comment by weshatheleopard** [comment]
From what I can understand, you are running your tests with warnings enabled. These messages can be safely ignored.

I will work on eliminating those warning messages, but it is not a priority right now.

**Comment by Dysp** [comment]
That is wonderful news. Thank you; I thought I was doing something really wrong.
