### ISSUE TITLE
Cannot add right border to merged cell

### ISSUE THREAD

**Issue by ardavis** [weshatheleopard/rubyXL#239]
It appears if I merge two cells, I can no longer add a right border to it. It does appear that bottom borders still work.

```
workbook = RubyXL::Workbook.new
worksheet = workbook[0]
worksheet.merge_cells(1,1, 1,2)

cell = worksheet.add_cell(1,1, '')
cell.change_border(:right, :thin)

workbook.write('test.xlsx')
```
I have noticed that if I initialize the 2nd cell in the merge and add the border to that, it works.

```
cell = worksheet.add_cell(1,2, '')
cell.change_border(:right, :thin)
```

Is it possible to add borders to a merged cell without initializing empty data in the cells behind the merge?

**Comment by weshatheleopard** [comment]
[Afraid not](https://poi.apache.org/faq.html#faq-N1013F).
