### ISSUE TITLE
RuntimeError: Unknown child node [x:fileVersion] for element [workbook]

### ISSUE THREAD

**Issue by ngiger** [weshatheleopard/rubyXL#240]
[Betriebe_20160823.xlsx](https://github.com/weshatheleopard/rubyXL/files/432913/Betriebe_20160823.xlsx)

With IRB (Ruby 2.3.1) I cannot parse this file.  
irb(main):001:0> require 'rubyXL'
=> true
irb(main):002:0> workbook= RubyXL::Parser.parse 'Betriebe_20160823.xlsx'
RuntimeError: Unknown child node [x:fileVersion] for element [workbook]
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyXL-3.3.21/lib/rubyXL/objects/ooxml_object.rb:155:in `block in parse'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in`block in each'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in`each'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyXL-3.3.21/lib/rubyXL/objects/ooxml_object.rb:144:in `parse'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyXL-3.3.21/lib/rubyXL/objects/ooxml_object.rb:440:in`block in parse_file'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/entry.rb:495:in `get_input_stream'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyXL-3.3.21/lib/rubyXL/objects/ooxml_object.rb:440:in`parse_file'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyXL-3.3.21/lib/rubyXL/objects/relationships.rb:91:in `block in load_related_files'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyXL-3.3.21/lib/rubyXL/objects/relationships.rb:76:in`each'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyXL-3.3.21/lib/rubyXL/objects/relationships.rb:76:in `load_related_files'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyXL-3.3.21/lib/rubyXL/objects/relationships.rb:179:in`load_relationships'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyXL-3.3.21/lib/rubyXL/objects/root.rb:66:in `parse_zip_file'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyXL-3.3.21/lib/rubyXL/parser.rb:8:in`block in parse'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb:102:in `open'
        from /home/niklaus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyXL-3.3.21/lib/rubyXL/parser.rb:7:in`parse'
        from (irb):2
        from /home/niklaus/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'

**Comment by arohr** [comment]
Hi Niklaus

I have the same problem here. Have you found a solution to this problem?

btw: wir kennen uns von früher (mindclue)...

Andy

**Comment by weshatheleopard** [comment]
@arohr do you have a sample file that exhibits this behavior?

**Comment by arohr** [comment]
@weshatheleopard Yes: [Aggregates.xlsx](https://github.com/weshatheleopard/rubyXL/files/3881151/Aggregates.xlsx)

**Comment by weshatheleopard** [comment]
@arohr: the 3rd party software was generating the file that isn't exactly up to spec (but not terribly out of spec either). Update the gem and try again.
