### ISSUE TITLE
How can i write Excel file directly to s3 using this gem?

### ISSUE THREAD

**Issue by sachin-metacube** [weshatheleopard/rubyXL#241]
I want to write the excel file directly AWS s3 please help me with this.

Please refer this SO Post.
http://stackoverflow.com/questions/39137804/how-write-excel-file-and-save-it-s3

Please help.

**Comment by weshatheleopard** [comment]
Technically, this is YOUR job as a developer to figure out how to utilize existing libraries to achieve the desired results. Right now you sound like "Mom, on the cover of this LEGO box there's a picture of a beautiful truck, but inside, there's only a bunch of parts. Please help me with this!". No. You are given the parts, and then figuring out how to make them into a whole is *your* job.

Regarding of your particular question: `workbook.write` writes file to the disk, whereas you need the file's data directly from memory, without the need to write it to the disk. You should use `workbook.stream` instead. It's in the documentation.
