### ISSUE TITLE
can't get borders of a cell

### ISSUE THREAD

**Issue by ryanlion** [weshatheleopard/rubyXL#242]
when i call row.cells[0].border_bottom
[DEPRECATION] `border_bottom` is deprecated.  Please use `get_border` instead.
nil

when i call row.cells[0].get_cell_border
*** NoMethodError Exception: private method `get_cell_border' called for #<RubyXL::Cell(0,0): "0", datatype = s, style_index = 0>

nil

**Comment by RKushnir** [comment]
Have you tried calling `get_border` as it suggests?

**Comment by weshatheleopard** [comment]
```
> require 'rubyXL'
> doc=RubyXL::Parser.parse('test/input/test.xlsx')
> doc[7][0][0].get_border :bottom
 => "thin"
```
