### ISSUE TITLE
Sorting by columns & rows

### ISSUE THREAD

**Issue by holaymolay** [weshatheleopard/rubyXL#255]
Does rubyXL support sorting by column or row? I have not seen mention of it in the documentation.

If no, is it a desirable feature? Would you welcome a contributor to add the feature?

**Comment by weshatheleopard** [comment]
I do not exactly understand how you mean. Certainly you can rearrange cells all you want by simply copying them from old location to the new one. But you should remember that it's much more complex than that, because you will also need to copy respective styles, references, etc.
