### ISSUE TITLE
Any way to autoresize columns?

### ISSUE THREAD

**Issue by dciotoli** [weshatheleopard/rubyXL#264]
I assume you could do something where you get the font and number of chars in the font and pick a size based on that, but I feel there must be a better way? Would rather not make a weird solution that is specific to fonts and requires me to update it every time i use a new font.

**Comment by weshatheleopard** [comment]
`RubyXL` is (yet, at least) not a full implementation of `Excel`. As such, it has no idea about fonts (other than their names) and has no way of determining what it will look like on the screen.

However, if you can come up with some idea, I do not have anything against pulling it into the main codebase. For what `Excel` does regarding column width, see [https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.column%28v=office.14%29.aspx](this document).

**Comment by tomlobato** [comment]
> I assume you could do something where you get the font and number of chars in the font and pick a size based on that, but I feel there must be a better way? Would rather not make a weird solution that is specific to fonts and requires me to update it every time i use a new font.

Update col width after any .add_cell:
```ruby
@ws.add_cell row, col, val
w = val.to_s.size * 1.1
if w > @ws.get_column_width(col)
 @ws.change_column_width(col, w)
end
```
