### ISSUE TITLE
Excel complain of wrong value for zoomScaleSheetLayoutView

### ISSUE THREAD

**Issue by xykox** [weshatheleopard/rubyXL#265]
According to [Microsoft documentation](https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.sheetview.zoomscalesheetlayoutview(v=office.14).aspx), zoomScaleSheetLayoutView and ZoomScalePageLayoutView should be Integer. But [rubyXL defines zoomScaleSheetLayoutView as boolean](https://github.com/weshatheleopard/rubyXL/blob/v3.3.23/lib/rubyXL/objects/worksheet.rb#L597)

**Comment by weshatheleopard** [comment]
Should release the gem later today.
