### ISSUE TITLE
Different Results on Different Runs

### ISSUE THREAD

**Issue by AlexArthur93** [weshatheleopard/rubyXL#277]
So a bit of background. I'm trying to parse an xlsx sheet that we get from a service provider and output it our own format. They use background fills on the cells to mark the days where they are available.
I have looped through the sheets and extracted the background colour of each like so:
`bg = cell && cell.fill_color ` 

This was working fine, but I've run the script a few times now and now most of the colours are not being detected at all. (Only a single cell with a fill colour has it's colour extracted).

**Comment by weshatheleopard** [comment]
Can you provide a sample spreadsheet you are having issues with so I can investigate?

**Comment by AlexArthur93** [comment]
This is the specific spreadsheet I'm having an issue with : https://tracint-my.sharepoint.com/personal/alex_arthur_trac_com/_layouts/15/guestaccess.aspx?docid=088bb7f851f3f4d8ab5ae8427cef9c1ac&authkey=AdHzqdVg4e7N_HnbCuqhUEE&expiration=2018-01-16T08%3A29%3A56.000Z&e=1002184f9d914d51886f1b95cf9ab0e8.

**Comment by weshatheleopard** [comment]
@AlexArthur93 : can you try the `color_manipulation` branch and see if it suits you? The colors seems to be a tiny bit off. but I can't figure out why.

**Comment by AlexArthur93** [comment]
Sorry I'm a bit of noob at this whole thing. How'd I go about replacing  the current version I have?
