### ISSUE TITLE
Workbook.write saves XLSX as a zip file with folders full of XMLs instead of as an XLSX

### ISSUE THREAD

**Issue by zackyangzinc** [weshatheleopard/rubyXL#279]
I understand that XLSX's are in fact zip files with XML files -- would really appreciate help in figuring out how to get the file returned to me to be a true XLSX.  Workbook.write works just fine when I write to an existing XLSX but it does not work when I try to create a fresh XLSX.

**Comment by zackyangzinc** [comment]
Also note that I'm persisting the object to paperclip and I'm doing that during a File.open. 

    File.open(file_path) do |processed_file|
      processed_file.class.class_eval { attr_accessor :original_filename, :content_type }
      processed_file.original_filename = shipping_params[:qqfile].original_filename
      shipping_request.initial_document = processed_file
    end

**Comment by weshatheleopard** [comment]
I don't exactly understand what you need. Are you talking about `workbook#stream`, by any chance
