### ISSUE TITLE
Is there a way to read in an XLSX file as a stream?

### ISSUE THREAD

**Issue by myfitment** [weshatheleopard/rubyXL#290]
Can I do this in the same way as the ```creek``` gem? I don't see from the README that I can. I see this:

```
workbook = RubyXL::Parser.parse_buffer(buffer)
workbook.stream
```

But I'm not clear on what either of those methods accomplish. Or what ```buffer``` even is.

```creek``` is unable to stream files created by the ```Axlsx``` gem without them first being opened and then saved manually in Excel, so if I can accomplish that here then that will be the best.

**Comment by weshatheleopard** [comment]
> Or what `buffer` even is.

Previous line:

> It can also operate on **`StringIO`** objects, thus eliminating the need to save the xlsx file to disk.
