### ISSUE TITLE
Parse_buffer not available

### ISSUE THREAD

**Issue by zackyangzinc** [weshatheleopard/rubyXL#292]
NoMethodError (undefined method `parse_buffer' for RubyXL::Parser:Class) -- is this even defined?

**Comment by weshatheleopard** [comment]
No idea what you are doing, but works for me:

```
001 > require 'rubyXL'
 => true
002 > RubyXL::Parser.parse_buffer(File.open("test.xlsx", "rb").read)
```

**Comment by hjansen** [comment]
I have the same problem. When i include this gem in my rails app via 

`gem 'rubyXL'`

I get 

`undefined method 'parse_buffer' for RubyXL::Parser:Class`

as well.

Do i have to sepcify a version or sth. like that ?

**Comment by hjansen** [comment]
I seems that the gem that is being downloaded by default is another version (3.1.0):

`Using rubyXL 3.3.29 (was 3.1.0) from https://github.com/weshatheleopard/rubyXL.git (at master@74b4717)`

I had to define it like that:

`gem 'rubyXL', '3.3.29'`
