### ISSUE TITLE
Unknown child node [xr:revisionPtr] for element [workbook] after Excel for mac update [16.11.1 (180319)]

### ISSUE THREAD

**Issue by lihuishe** [weshatheleopard/rubyXL#299]
Hi

It seems the gem has trouble paring any excel sheets for newest Excel for 
version for excel:  [16.11.1 (180319)]
error message:
Unknown child node [xr:revisionPtr] for element [workbook]

**Comment by weshatheleopard** [comment]
Update your gem. This has been [fixed recently](https://github.com/weshatheleopard/rubyXL/commit/8743bd2a0dbe6d7b57a40ea092c08293ec69f195).
