### ISSUE TITLE
Unknown child node [xr:revisionPtr] for element [workbook]

### ISSUE THREAD

**Issue by myfitment** [weshatheleopard/rubyXL#301]
I've been seeing this error intermittently. When the files are opened and resaved in Excel, the problem goes away. Here is a link to a file that is currently causing this error:

https://www.dropbox.com/s/6f2xmso5re8xbk1/GKT-A-HD--040318.xlsx?dl=0

**Comment by weshatheleopard** [comment]
[Search is your friend](https://github.com/weshatheleopard/rubyXL/issues/299)

**Comment by myfitment** [comment]
Whoops. I did search but quit after my first result here. Thanks, problem solved.

**Comment by stefsava** [comment]
I have this message with the latest version of the gem (3.4.5).
The workaround I am using is to save the file generated by Excel with LibreOffice (in xlsx of course).

[empty.xlsx](https://github.com/weshatheleopard/rubyXL/files/3482425/empty.xlsx)
