### ISSUE TITLE
doesn't work on jruby

### ISSUE THREAD

**Issue by ahorek** [weshatheleopard/rubyXL#310]
environment
```
jruby 9.2.1.0-SNAPSHOT (2.5.0) 2018-07-07 9d52bae Java HotSpot(TM) 64-Bit Server VM 9.0.4+11 on 9.0.4+11 +jit [linux-x86_64]
nokogiri 1.8.4 (java)
rubyXL 3.3.29
```

script
```
require 'rubyXL'
RubyXL::Workbook.new.stream
```

Traceback (most recent call last):
       16: from org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
       15: from org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:360)
       14: from org.jruby.ir.instructions.CallBase.interpret(CallBase.java:522)
       13: from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:80)
       12: from org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
       11: from org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:103)
       10: from org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        9: from org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:360)
        8: from org.jruby.ir.instructions.CallBase.interpret(CallBase.java:522)
        7: from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:80)
        6: from nokogiri.XmlNode$INVOKER$s$0$0$rbNew.call(XmlNode$INVOKER$s$0$0$rbNew.gen)
        5: from nokogiri.XmlNode.rbNew(XmlNode.java:289)
        4: from nokogiri.XmlNode.init(XmlNode.java:331)
        3: from org.apache.xerces.dom.CoreDocumentImpl.createElementNS(Unknown Source)
        2: from org.apache.xerces.dom.ElementNSImpl.<init>(Unknown Source)
        1: from org.apache.xerces.dom.ElementNSImpl.setName(Unknown Source)
Java::OrgW3cDom::DOMException (NAMESPACE_ERR: An attempt is made to create or change an object in a way which is incorrect with regard to namespaces.)

**Comment by weshatheleopard** [comment]
https://github.com/weshatheleopard/rubyXL/issues/188
