### ISSUE TITLE
creation and configuration of panes (split)

### ISSUE THREAD

**Issue by koenhandekyn** [weshatheleopard/rubyXL#312]
is there a way with the current API to create panes and split configurations? thanks for any hints if possible, i'll write out some documentation from it and contribute it to the main readme.

**Comment by weshatheleopard** [comment]
```
require 'rubyXL'
workbook = RubyXL::Workbook.new
worksheet = workbook[0]

worksheetview = RubyXL::WorksheetView.new
worksheetview.pane = RubyXL::Pane.new(:top_left_cell => RubyXL::Reference.new(4,8), :x_split => 4000, :y_split => 2000)

worksheetviews = RubyXL::WorksheetViews.new
worksheetviews << worksheetview
worksheet.sheet_views = worksheetviews
workbook.save "test.xlsx"
```

(Obviously, use your particular numbers).
Regarding calculation for `x_slit` and `y_split`, see https://stackoverflow.com/questions/4577546/calculating-height-width-and-ysplit-xsplit-for-open-xml-spreadsheets

**Comment by koenhandekyn** [comment]
thanks a lot for the hint.

first i got the split variant working. the calculations for the width from the above referenced perl script where correct but not for the height, but some trial and error solved that.

but it seemed that i needed the 'frozenSplit' variant and for me still unknown reasons i got it to work only with xsplit=1 and ysplit=1 values (inspired from other places on the web), and the result in Mac OS X Office at least seems correct, the previous values rendered corrupt xlsx files. 

```
      worksheetview = RubyXL::WorksheetView.new
      worksheetview.pane = RubyXL::Pane.new(:top_left_cell => RubyXL::Reference.new(1,1),
                                            :x_split => 1,
                                            :y_split => 1,
                                            :state => 'frozenSplit')

      worksheetviews = RubyXL::WorksheetViews.new
      worksheetviews << worksheetview
      worksheet.sheet_views = worksheetviews
```
