### ISSUE TITLE
Error when using the gem with ruby prior to 2.1

### ISSUE THREAD

**Issue by bacchir** [weshatheleopard/rubyXL#313]
I'm having trouble using this gem with ruby prior to 2.1 in spite of the fact that there's no required minimum ruby version on the gem definition.

The problem is caused by this [line](https://github.com/weshatheleopard/rubyXL/blob/master/lib/rubyXL/convenience_methods.rb#L1266)

**Comment by weshatheleopard** [comment]
I'll take care of that in a few minutes.

**Comment by bacchir** [comment]
Hey @weshatheleopard I created a PR for it already: https://github.com/weshatheleopard/rubyXL/pull/314 please take a look 😊
