### ISSUE TITLE
RubyXL replaces empty <c></c> cells with the value of A1 cell

### ISSUE THREAD

**Issue by rpasta42** [weshatheleopard/rubyXL#316]
This bug was discovered when reading Excel files generated with OpenPyXL library.

Normal cells contain XML tags that look like this: `<c><v></v></c>`
OpenPyXL replaces empty strings with `<c></c>` tag, while other libraries omit the `<c>` tag entirely.

Most other libraries and Excel correctly interpret `<c></c>` tag as empty cell, but RubyXL replaces these tags with the value of A1 cell.

**Comment by weshatheleopard** [comment]
@rpasta42 Can you please provide a sample `xlsx` file that exhibits that behavior, so I could reproduce the bug locally?

**Comment by weshatheleopard** [comment]
@rpasta42 I did some experiments of my own but I'm unable to reproduce the behavior you describe. Please provide the sample file.
