### ISSUE TITLE
defining names for cells (to be used in formulas)

### ISSUE THREAD

**Issue by koenhandekyn** [weshatheleopard/rubyXL#319]
is it possible to define cell names to be used in formula's ? i can't find anything online. it must be part of the spec somehow as in a comparable python lib it seems to be 'exposed' (https://xlsxwriter.readthedocs.io/example_defined_name.html). willing to implement if some hint can be given.

![image](https://user-images.githubusercontent.com/710262/52211372-feaea600-2889-11e9-8d56-ac0310a48e84.png)

**Comment by weshatheleopard** [comment]
```
doc = RubyXL::Workbook.new
doc.defined_names ||= RubyXL::DefinedNames.new
doc.defined_names << RubyXL::DefinedName.new({:name => 'MY NAME', :reference => "Sheet1!$A$2"})
```

**Comment by koenhandekyn** [comment]
thanks for the prompt response.

for others interested, i've monkey patched the worksheet class with the below helper that can be used similar to other methods

        worksheet.define_name(1,1, 'myname')

it creates an absolute cell reference for the coordinates in the given sheet and than adds the name to the defined names using the provided snippet from above.

```
class RubyXL::Worksheet
  def define_name(row, column, name)
    workbook.defined_names ||= RubyXL::DefinedNames.new
    reference = "'#{sheet_name}'!#{RubyXL::Reference.ind2ref(row, column)}"
    workbook.defined_names << RubyXL::DefinedName.new({:name => name, :reference => reference})
  end
end
```

**Comment by sixtyfive** [comment]
Perhaps others stumbling over #94 might also be interested in this Issue here.
