### ISSUE TITLE
issue when trying to "unset" the locked status of a cell

### ISSUE THREAD

**Issue by koenhandekyn** [weshatheleopard/rubyXL#320]
i'm trying to set the locked status to false (it seems the default is true) with the following code

```
    xf = get_cell_xf.dup
    xf.apply_protection && xf.protection.locked = false
    puts "*"*80
    puts xf.inspect
    puts "*"*80
```
but the locked remains true and if i inspect the xf object just after the change i'm also seeing that apply_protection still is nil and protection itself also is nil

`#<RubyXL::XF:0x00007fb0314f6058 @local_namespaces=nil, @num_fmt_id=166, @font_id=6, @fill_id=0, @border_id=0, @xf_id=nil, @quote_prefix=nil, @pivot_button=nil, @apply_number_format=true, @apply_font=true, @apply_fill=nil, @apply_border=nil, @apply_alignment=nil, @apply_protection=nil, @alignment=nil, @protection=nil>`

i'm probably doing something "stupid" somewhere.
thanks for the suggestion / tips

**Comment by weshatheleopard** [comment]
Yes, you are doing something stupid: namely, you are *reading* `apply_protection` and `protection` objects (and encounter none, obviously), where you have to actually *create* them.

Off the top of my head (I do not have time right now to run this code and ensure it is correct), the code should look like:
```
old_xf = get_cell_xf
new_xf = old_xf.dup
if old_xf.protection then
  new_xf .protection = old_xf .protection.dup
else
  new_xf .protection = RubyXL::Protection.new
end
new_xf .protection.locked = false
new_xf .apply_protection = true
self.style_index = workbook.register_new_xf(new_xf)
```

**Comment by koenhandekyn** [comment]
thanks for the code proposal ! it worked and i turned it into the following convenience method on a Cell for possible other interested readers. 

```
class RubyXL::Cell
  def unlock
    xf = get_cell_xf.dup
    xf.protection = xf.protection&.dup || RubyXL::Protection.new
    xf.protection.locked = false
    xf.apply_protection = true
    self.style_index = workbook.register_new_xf(xf)
  end
end
```
