### ISSUE TITLE
Update ruby version requirement on rubygems.org

### ISSUE THREAD

**Issue by evanthegrayt** [weshatheleopard/rubyXL#326]
According to rubygems.org:

![image](https://user-images.githubusercontent.com/12698076/53837731-e39e8700-3f58-11e9-8e03-acad6fc36b9c.png)

But the changes since `RubyXL 3.4.0` broke compatibility with `Ruby < 2.1`. The new convenience method modules use the following:
```ruby
RubyXL::Cell.include(RubyXL::CellConvenienceMethods)
```
But `Module#include` is a private method before 2.1.  The gem *could* be updated to use:
```ruby
RubyXL::Cell.send(:include, RubyXL::CellConvenienceMethods)
```
...or the info on https://rubygems.org/gems/rubyXL should be updated.

I know most people won't be using a ruby that's this old, but we're stuck with an old version where I work, so this info would be appreciated.

**Comment by weshatheleopard** [comment]
Thank you for the info. I'll try to keep this gem functioning on older versions as long as possible, however I can't test every single one myself, so your input is appreciated. `3.4.2` should be compatible with <2.1 again.

**Comment by evanthegrayt** [comment]
Thank you so much!
