### ISSUE TITLE
Writing to a file causes `undefined method `href' for nil:NilClass` error

### ISSUE THREAD

**Issue by Plotist** [weshatheleopard/rubyXL#332]
I've been trying both `write` and `stream` on that with a same result.
```
path = "./tmp/some.xlsx"
workbook = RubyXL::Parser.parse(path)
workbook.write(path)
workbook = RubyXL::Parser.parse(path)
```
Results in on the last step
`=> NoMethodError: undefined method 'href' for nil:NilClass
from /Users/plotist/.rvm/gems/ruby-2.6.2@rubyxl-my-gemset/gems/rubyXL-3.4.2/lib/rubyXL/objects/ooxml_object.rb:147:in 'block in parse'`

**Comment by weshatheleopard** [comment]
I tried on my test file and did not encounter any problems. I believe the problem is in the file you are trying to parse. Please attach it to this bug so I can take a look.

**Comment by Plotist** [comment]
I can't seem to find one. Sorry to bother you!
I'll jump back and will upload the one it was failing on if I will be able to find it.
