### ISSUE TITLE
undefined method `change_row_font_size' - rails 52 ?

### ISSUE THREAD

**Issue by koenhandekyn** [weshatheleopard/rubyXL#333]
i'm fighting an issue with a very strange class loading issue as it seems. somehow the convenience methods are not loaded correctly under rails 5.2? somehow with version 3.3.33 the issue doesn't exist.

**Comment by weshatheleopard** [comment]
I recommend that you read the [documentation](https://github.com/weshatheleopard/rubyXL/blob/master/README.rdoc), specifically the **Convenience methods** section.
