### ISSUE TITLE
index_in_collection fails when creating a worksheet manually

### ISSUE THREAD

**Issue by klobetime** [weshatheleopard/rubyXL#337]
The `index_in_collection` function on Row works fine when loaded from a file, but fails when a workbook is built manually using RubyXL:

```ruby
require 'rubyXL'

workbook = RubyXL::Workbook.new
worksheet = workbook[0]
worksheet.add_cell(0, 0, 'data')
row = worksheet.sheet_data.rows[0]
puts row.index_in_collection
```
The above snippet throws `.../gems/rubyXL-3.4.3/lib/rubyXL/objects/sheet_data.rb:156:in 'index_in_collection': undefined method '-' for nil:NilClass (NoMethodError)`

**Comment by weshatheleopard** [comment]
`index_in_collection` is a service method and is not supposed to be used by the end user (the values it uses are either loaded from the source file, or are initialized on spreadsheet save). Why do you feel the need to use that method?

**Comment by klobetime** [comment]
I didn't see anything in the docs about it being something I shouldn't use.  I have an app where I loop through a sparse sheet only processing rows with data; index_in_collection is a very handy way of finding where I am without keeping track manually.

**Comment by weshatheleopard** [comment]
As a workaround, you can force populating of `r` elements of a worksheet by calling `before_write_xml` on it. But I recommend 'keeping track manually' as it would be faster and more accurate.
