### ISSUE TITLE
Using change_contents and then saving the file has a weird effect

### ISSUE THREAD

**Issue by afrustagli** [weshatheleopard/rubyXL#339]
Hi there,

When I use change_contects(val) on a cell, then save the file the resulting spreadsheet behaves strangely. If I open it in Excel the value I changed is displayed in the cell, but if I click on the cell nothing appears in the formula bar. If I double click the cell to edit it the value disappears completely. I'm I doing something wrong, or is this a bug?

**Comment by weshatheleopard** [comment]
RubyXL is not a *perfect* reproduction of Excel (in order for it to be, by definition, just about as much effort need to put into it as was put into Excel itself). As such, snafus like you described can potentially happen. I'm fairly certain that in this particular case it depends on your source file, so can you please supply sample of the code/data you are working with, so I can reproduce the bug on my side?

**Comment by afrustagli** [comment]
Sure!  It's attached.

I also tried to use add_cell instead of change_contents, and while that seems to add values correctly it ends up messing up the cells' borders. Using change_border on the cell gives:

`NoMethodError: undefined method `modify_border' for #<RubyXL::Workbook:0x007f8d12ca1f38>`

And I'm definitely referencing the cell object even though the error is on the workbook object.

Thanks for looking into this! I really appreciate it!
[AgentAllocationForCross-DockedProduct.xlsx](https://github.com/weshatheleopard/rubyXL/files/3307098/AgentAllocationForCross-DockedProduct.xlsx)

**Comment by weshatheleopard** [comment]
I'm unable to reproduce your situation. Content seems to change properly and the cell does not appear blank in the output.

In order to use `modify_border` you should not forget to include workbook convenience methods (see this gem's documentation).
