### ISSUE TITLE
Dates returning as Fixnum

### ISSUE THREAD

**Issue by maxstudener** [weshatheleopard/rubyXL#34]
When i enter 6/1/2012 excel auto formates it to a date and apply the value as 6/1/12 and then when i parse the spread sheet i get 41061 as a Fixnum returned

**Comment by homezada** [comment]
formatted_date = Date.new(1900) + date_integer

..is out by two days. See here for a workaround:

http://www.databasically.com/2011/04/22/rubys-parseexcel-and-the-extra-date/

**Comment by weshatheleopard** [comment]
@homezada: not sure what you are talking about. Can you provide a test case? Dates work as expected for me.
