### ISSUE TITLE
How to make a cell dropdown

### ISSUE THREAD

**Issue by Reenamary** [weshatheleopard/rubyXL#340]
Hello,

I am using RubyXL gem to read and write a xlsm file.In my project there is a field Country which should diplay all list of countries in a dropdown in xlsm.And I have tried with DataValidation but it is not showing dropdown list on that cell.My code is given below.

 workbook        = RubyXL::Parser.parse(dest_file_path)
 worksheet1     = workbook["Form"]
 content            = ['Afghanistan','Albania,'Algeria']
 formula            = RubyXL::Formula.new(expression: content)
 loc                   = RubyXL::Reference.new(1, 1048000, 2, 2)
 worksheet1.data_validations = RubyXL::DataValidation.new(prompt_title: nil, prompt: nil,
                 sqref: loc, formula1: formula,
                 type: 'list', show_input_message: true,
                 show_drop_down: true) 
How should I associate DataValidation to a specific worksheet ? Is there any other way I can do this? Could anyone please help.

**Comment by weshatheleopard** [comment]
The issue you are talking about is with the construction of proper OOXML data structures, not with `RubyXL` per se. I would recommend the following course of action:

1) Using Excel, create an empty spreadsheet and save it;
2) In that spreadsheet, create the dropdown you are talking about in one cell. Save the spreadsheet again under a different name;
3) Unzip both spreadsheets (they are actually ZIP files that contain a bunch of other files inside) and compare the contents.

You will be able to see what is different between the two and what elements and in which order you need to create.

Then after you are able to successfully  do so, you can submit a pull request for a new convenience method to be included with this gem.

(I will try to look into this, but that's given I have free time, etc.)

**Comment by Tresky** [comment]
I know this is old, but I recently did a bit of digging into this and thought I'd leave my findings here for anyone who might want to implement this feature.

Creating a new blank spreadsheet with a single data validation dropdown in Excel creates this XML result.
```
<dataValidations count="1">
  <dataValidation type="list" allowBlank="1" showInputMessage="1" showErrorMessage="1" sqref="A1">
    <formula1>"USA,France,Spain"</formula1>
  </dataValidation>
</dataValidations>
```

When you use the given code above to create a data validation with RubyXL, you get the following result which, when opened in Excel, triggers the "corrupted file; need to repair" dialog sequence.
```
<dataValidations type="list" showDropDown="1" showInputMessage="1" sqref="E5">
  <formula1>["Afghanistan", "Albania", "Algeria"]</formula1>
</dataValidations>
```

It seems to me that RubyXL is currently just implementing dataValidations incorrectly in XML for whatever reason (maybe the spec changed, etc, idk).

**Comment by weshatheleopard** [comment]
@Tresky  yes, the OP's code is wrong. I probably should look at it at some point but it has to be a bit later.

**Comment by Tresky** [comment]
Roger that. Whenever you get a chance, it would be very helpful. This might be a good thing to include in the Readme in the future.

**Comment by Tresky** [comment]
After looking into this a bit more and digging through the code, I figured this one out. Hopefully, this code will benefit some other traveller who is in search of an answer to this question.

Here's my discovery on how to make this happen using the same example as the OP.
```
# Instantiate a new DataValidations instance for the worksheet.
# This acts as a container for all of the validations you want on the whole sheet.
worksheet.data_validations = RubyXL::DataValidations.new


# To make the list come out correct in the spreadsheet, I had to join
# the array and put double quotes around the string.
content = ['Afghanistan','Albania','Algeria']
formula = RubyXL::Formula.new(expression: "\"#{content.join(',')}\"")

# Push a new DataValidation instance into the above object;
# Seems like you should do this exact process for every dropdown you want
# to add anywhere else in the worksheet.
worksheet.data_validations << RubyXL::DataValidation.new(
  prompt_title: nil,
  prompt: nil,
  sqref: RubyXL::Reference.new(0, 0) # X and Y coordinate, 
  formula1: formula,
  type: 'list', show_input_message: true
  # Interestingly enough, when this option is included, the XML has a showDropDown="1"
  # on it, but the dropdown doesn't show. When you remove this option, the XML value is removed
  # and the dropdown shows. So just exclude this. The dropdown shows by default.
  # show_drop_down: true
)
```

**Comment by weshatheleopard** [comment]
Good job, you beat me to it :) That (off my memory) seems to be the absolutely correct way to do it. I will polish it a little bit and make a convenience method out of it.

**Comment by Tresky** [comment]
Great! Looking forward to it. :+1:

**Comment by weshatheleopard** [comment]
(sighs) and now I just started down the rabbit hole. There's a multitude of data validations ('list' being but one of them). There are very specific rules on how strings that are passed to formula are to be escaped. (Quotes replaced with double quotes; if commas are present, then string must be in quotes, etc.) As always, what looks like a quick-and-easy task, is anything but.

**Comment by Tresky** [comment]
Such is the life of development. Lol problems are always deeper than originally expected

**Comment by luizlojaifg** [comment]
Thanks, buddy. I think you solved my problem. Thank you a lot. May God be with you, dude.
