### ISSUE TITLE
How to save the existing Excel in the format of HTML?

### ISSUE THREAD

**Issue by Rajagopalan-M** [weshatheleopard/rubyXL#342]
I don't know whether this feature is available. I don't find any reference for that so far. I am able to do this in Excel by clicking "save as" and giving the name of the file and then choosing Web Page(*.htm,*.html)? 

I have looked into the write method which is actually alias for save method which throws the error If the given format is not .xlsx .xlsm.

> unless %w{.xlsx .xlsm}.include?(extension.downcase)
>         raise "Unsupported extension: #{extension} (only .xlsx and .xlsm files are supported)."
>       end

Can anyone tell me whether any way we can save this Excel into Web Page(*.htm,*.html) format? I can do this manually so I believe there must be some way or some method to accomplish this task.

**Comment by weshatheleopard** [comment]
> I don't know whether this feature is available

I'm sorry, this is not a support forum.
