### ISSUE TITLE
FR (?): Set cell padding

### ISSUE THREAD

**Issue by sixtyfive** [weshatheleopard/rubyXL#348]
Is there any way (or if not, would it be feasible to implement such a thing?) to set a cell's top/bottom/lef/right padding in millimeters like can be done from within Excel or Calc (right mouse button on cell(s) > "Format cell" > "Borders" > "Padding")? For example `worksheet.get_padding(side = nil)` and `worksheet.change_padding(row, col, side = nil)`, where a `side` of `nil` would mean "all sides at once")...

**Comment by weshatheleopard** [comment]
When I right-click on a cell, I can do  Format Cells > Border, but there's no "padding" option on that dialog. So I'm not sure what this request is about.

**Comment by sixtyfive** [comment]
![image](https://user-images.githubusercontent.com/192860/168036437-7da96a76-d4c0-4d53-b2ae-9189d28afd5f.png)

**Comment by sixtyfive** [comment]
Interesting, That picture came from LibreOffice Calc. I didn't think that it would have any features that Microsoft Excel doesn't have. But doing what you asked and then saving as .xlsx, closing, and opening the document again causes the padding to be lost. Setting the padding, daving as .ods, closing, and opening the document again causes it to be retained. The I have my answer. Thank you, Wesha!

**Comment by weshatheleopard** [comment]
It feels like cell padding is not supported in the `SpreadsheetML` specification, so it cannot be supported by `rubyXL`. If I'm wrong, feel free to correct me.

**Comment by sixtyfive** [comment]
I agree.
