### ISSUE TITLE
Changing border works; changing border color doesn't

### ISSUE THREAD

**Issue by sixtyfive** [weshatheleopard/rubyXL#349]
```ruby
[...]
    [:left, :right].each do |side|
      @worksheet.change_column_border(i, side, 'thin')
      @worksheet.change_column_border_color(i, side, '999999')
    end
[...]
```

works fine on any file I've thrown at it with the `change_column_border_color` line commented out. But when that line is not commented out, this happens:

```
NoMethodError: undefined method `cells' for nil:NilClass
```

How do I find out what's going wrong here?

**Comment by KelvinWB** [comment]
I am with a similar problem with the "change_fill" method. 
I try to run the method and this happens:

NoMethodError: undefined method `change_fill'

**Comment by weshatheleopard** [comment]
See "Convenience methods" section in the documentation.

**Comment by sixtyfive** [comment]
Thanks Weshat, I'll run your MWE on one of my files. If it WFY on a new Workbook then perhaps that's where the problem lies...
