### ISSUE TITLE
change_font_size not found in 3.4.6

### ISSUE THREAD

**Issue by yratanov** [weshatheleopard/rubyXL#351]
When I try to do this in 3.4.6:
```ruby
cell = sheet.add_cell(0, 0, "text")
cell.change_font_size(14)
```

It throws error that method not found. Same for other methods from `WorkbookConvenienceMethods`.

It works in `3.3.29` though.

**Comment by weshatheleopard** [comment]
Please read the section named "Convenience methods" in the [documentation](https://github.com/weshatheleopard/rubyXL/blob/master/README.rdoc).
