### ISSUE TITLE
Custom date formatting not applies to cell

### ISSUE THREAD

**Issue by avdept** [weshatheleopard/rubyXL#352]
So I have pretty simple code, which puts into cell date and applies formatting

```
cell.change_contents(Date.today.strftime('%d.%m.%Y %H:%M:%S'))
cell.set_number_format('ddd mmm dd, yyyy')
```

The problem - formatting not applied. However if you go to formula bar and hit enter, formatting applies correctly. Any ideas what am I doing wrong?

**Comment by weshatheleopard** [comment]
The formatting does get applied. The problem here is that you set the cell to contain a textual representation of the date, not the date itself! Your code should be

```
cell.change_contents(Date.today)
cell.set_number_format('ddd mmm dd, yyyy')
```

Then it all works.

**Comment by avdept** [comment]
Well, yes, it works for Date, however is there a chance to have same behavior for DateTime objects?
