### ISSUE TITLE
Support question - using rubyXL to get checkbox control and value

### ISSUE THREAD

**Issue by JimEvansIntox** [weshatheleopard/rubyXL#359]
I am trying to retrieve a checkbox control and its value using rubyXL and haven't yet figured out how to do so. (Finding cell values was very easy and thank you for that.) Google has been unsuccessful and I've started slogging through the docs, but any help would be appreciated.

Additional information: Poking around in the xlsx archive, I learned it is in `xl\drawings\vmlDrawing1.vml` so now figuring out how to access that via rubyXL

**Comment by JimEvansIntox** [comment]
Found what I needed in Workbook#generic_storage where generic_storage[n].class = 'RubyXL::VMLDrawingFile'.
Then:
```
doc =  Nokogiri.XML(workbook.generic_storage[n].data)
shape_node = xpath("//v:shape") # this is assuming exactly one shape_node
if shape_node.xpath("x:ClientData").attribute("ObjectType").value == 'Checkbox'
  checkbox_label = shape.xpath("v:textbox/div").text.gsub("\n",'').squeeze(" ")
  checkbox_status = shape.xpath("x:ClientData/x:Checked").text.gsub("\n",'').squeeze(" ")
  checkbox_anchor = shape.xpath("x:ClientData/x:Anchor").text.gsub("\n",'').gsub(" ","")
          # first digit is left column, 3rd digit is top row, starts at 0,0
end
```

**Comment by weshatheleopard** [comment]
I've never encountered VML files in excel before. If you can attach your file here for my reference, I might be able to make these recognizable bu this gem.
