### ISSUE TITLE
The  cells returned by merged_cells is not complete

### ISSUE THREAD

**Issue by kematy** [weshatheleopard/rubyXL#363]
The  cells returned by merged_cells is not complete，Many merged cells are not recognized 
       merged_cells_hash={}
       worksheet.merged_cells.each do |mc|
          range=mc.ref.to_s.split(':')
          s_range=RubyXL::Reference.ref2ind(range[0])
          e_range=RubyXL::Reference.ref2ind(range[1])
          merged_cells_hash[[s_range[0],e_range[0]]]=[s_range[1],e_range[1] ]
       end
return：
{[46, 47]=>[26, 26], [48, 49]=>[26, 26], [42, 43]=>[26, 26], [38, 43]=>[1, 1], [44, 45]=>[26, 26], [44, 49]=>[1, 1], [38, 39]=>[26, 26], [40, 41]=>[26, 26], [34, 35]=>[26, 26], [36, 37]=>[26, 26], [30, 31]=>[26, 26], [26, 31]=>[1, 1], [32, 33]=>[26, 26], [32, 37]=>[1, 1], [26, 27]=>[26, 26], [28, 29]=>[26, 26], [22, 23]=>[26, 26], [24, 25]=>[26, 26], [18, 19]=>[26, 26], [14, 19]=>[1, 1], [20, 21]=>[26, 26], [20, 25]=>[1, 1], [14, 15]=>[26, 26], [16, 17]=>[26, 26], [10, 11]=>[26, 26], [12, 13]=>[26, 26], [6, 7]=>[26, 26], [2, 7]=>[1, 1], [8, 9]=>[26, 26], [8, 13]=>[1, 1], [2, 3]=>[26, 26], [4, 5]=>[26, 26], [0, 1]=>[2, 2], [0, 0]=>[25, 46], [1, 1]=>[43, 46]}
Many merged cells are not recognized

**Comment by weshatheleopard** [comment]
You are doing something wrong. Your code makes no sense, but one thing I can tell is that the line 

` range=mc.ref.to_s.split(':')`

should NOT be there.  `Reference`  handles that already:

```
> r = RubyXL::Reference.new("a1:b4")
 => #<RubyXL::Reference @row=-1 @col=-1>
> r = RubyXL::Reference.new("D2:F4")
 => #<RubyXL::Reference @row_range=1..3 @col_range=3..5>
> r.first_col
 => 3
> r.last_col
 => 5
> r.first_row
 => 1
> r.last_row
 => 3
```
