### ISSUE TITLE
Can't modify frozen String

### ISSUE THREAD

**Issue by rockorequin** [weshatheleopard/rubyXL#364]
I encountered a spreadsheet that gave me a "FrozenError (can't modify frozen String: "")" when I tried to read one of the values with worksheet[x][y].value.

The issue is in class RichText < OOXMLObject (objects/text.rb). The to_s method does:

```
      str = t.to_s
      r && r.each { |rtr| str << rtr.to_s if rtr }

```
but in this case t was nil, and nil.to_s is a frozen String.

Changing the code to this fixes the problem:

```
      str = t ? t.to_s : ""
      r && r.each { |rtr| str << rtr.to_s if rtr }
 
```

**Comment by weshatheleopard** [comment]
Already fixed, long time ago: https://github.com/weshatheleopard/rubyXL/commit/f0ed6a28dd4f5a1b39e64123be6dbfcdee439145 . Update the gem.

**Comment by rockorequin** [comment]
Oh sorry, bundle had locked it and I stupidly didn't think to check!
