### ISSUE TITLE
Unable to change a cell

### ISSUE THREAD

**Issue by nconsulting** [weshatheleopard/rubyXL#368]
I am unable to write new data in a cell. My code is:

`workbook = RubyXL::Parser.parse("test.xlsx")
worksheet = workbook[0]
counter = 0

books.each do |book|
      if not worksheet[counter].nil? and not worksheet[counter][0].nil?
        worksheet[counter][0].change_contents(book.title)
      else
        worksheet.add_cell(counter, 0, book.title)
      end
      counter = counter + 1
end`

The code works when I run it on a newly created XLSX file with Excel 365. It doesn't run the second time. I get the error - undefined method `change_contents' for #<RubyXL::Cell:0x000000000b14d498> . 

I get another error when I run the code on an existing XLSX file generated with Excel 2007 - undefined method `change_contents' for #<RubyXL::Cell(0,0): "0", datatype="s", style_index=nil>

What am I doing wrong?

**Comment by weshatheleopard** [comment]
> What am I doing wrong?

Forgetting to read the documentation, in particular [this section](https://github.com/weshatheleopard/rubyXL#label-Convenience+methods)?

**Comment by buncis** [comment]
here is the module docs https://www.rubydoc.info/github/weshatheleopard/rubyXL/RubyXL/CellConvenienceMethods
