### ISSUE TITLE
controlProperties not supported

### ISSUE THREAD

**Issue by piloos** [weshatheleopard/rubyXL#369]
When parsing and writing a xlsm file containing a button to trigger a macro, the written xlsm file opens with an error basically saying that the file is corrupt.

I noticed that the `[Content_Types].xml` file was missing the following line:
```
<Override PartName="/xl/ctrlProps/ctrlProp1.xml" ContentType="application/vnd.ms-excel.controlproperties+xml"/>
```

I could fix this by adding the `CONTENT_TYPE` constant in `storage.rb`
```
  class ControlPropertiesFile < GenericStorageObject
    CONTENT_TYPE = 'application/vnd.ms-excel.controlproperties+xml'
    REL_TYPE     = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/ctrlProp'
  end
```

I assume that this was intentionally left out to not make it _ms-excel_ specific, but maybe it could be an option...

BTW, cool gem!

**Comment by weshatheleopard** [comment]
Thanks! And no, it was not intentionally left out, it was just overlooked, and somewhat undertested as Excel has so many various features, and having *everything* work would be like re-writing the entire Excel!
