### ISSUE TITLE
RubyZip 2.3.0 changes workbook.stream encoding to ASCII-8BIT

### ISSUE THREAD

**Issue by kitsunde** [weshatheleopard/rubyXL#377]
While upgrading we ended up installing `rubyzip 2.3.0` from 2.2.0 which broke:

```ruby
workbook = RubyXL::Workbook.new
File.open('test.txt', 'w') { |f| f.write(workbook.stream.read) }
```

Because `workbook.stream` is now no longer UTF-8. As far as I can tell I'm not able to pass a setting to rubyXL to set the encoding of the stream so I'm pinning rubyzip to 2.2.0 for now.

It appears this https://github.com/rubyzip/rubyzip/issues/438 change is the root cause.

**Comment by weshatheleopard** [comment]
Um. I am confused.

1) Why are you using this strange construct: `File.open('test.txt', 'w') { |f| f.write(workbook.stream.read) }` when you can simply use `workbook.save "test.txt"` instead?
2) What exactly is the problem you are having? I just upgraded `rubyzip` to 2.3.0 (I use `ruby 2.7.1p83`) and ran that piece of code and did not encounter any issues.

**Comment by kitsunde** [comment]
1. That's a very good question that I also would ask the guy that wrote that code if he was still around.
2. It seems like this is only happening when it's running in rails/rspec but using irb everything is fine

Using `workbook.save` fixes it for me, thank you! I'm going to close this since I don't think I'll end up debugging the root cause.

**Comment by weshatheleopard** [comment]
OK. `workbook.stream` was specifically designed for use in Web servers that need to serve dynamically generated `xlsx` to clients, without wasting effort of "saving it to a tempfile and then returning the contents of tempfile". If that's not your use case, then you definitely should not use `stream`. And yes, poor programmers are a plague.
