### ISSUE TITLE
[Documentation] Could the documentation (main README.rdoc) briefly mention whether libreoffice is supported?

### ISSUE THREAD

**Issue by rubyFeedback** [weshatheleopard/rubyXL#378]
Copy from the title:

[Documentation] Could the documentation (main README.rdoc) briefly mention whether libreoffice is supported?

Reasoning: I sometimes need to autogenerate data into excel files. For the latter part I need to use gems; I think
I used another gem before but I can not remember the name, so I am looking for alternatives (rubyXL is actually
simpler to remember than that other gem :P).

At any rate, would it be possible for the main readme to briefly state whether libreoffice is supported as well? I
assume so, due to the standards supported in rubyXL, but I think it would be nice to have a brief mention fo this
in the main README too, to erase all doubt (or, if it is not supported, to briefly mention this as well). Thank you
for reading; feel free to close this issue at any moment in time.

**Comment by weshatheleopard** [comment]
`rubyXL` generates files in OpenXML format. As such, they are supposed to be universally readable.

How about you confirm that OpenOffice reads them fine, and then I will add that to the documentation?

**Comment by weshatheleopard** [comment]
Given the lack of reaction from the original reporter, I am closing this. There's no evidence that files generated by `rubyXL` are not supported by LibreOffice, and I do not have an _easy_ way to check that myself.
