### ISSUE TITLE
is_date? incorrectly detecting string as date

### ISSUE THREAD

**Issue by caramdache** [weshatheleopard/rubyXL#382]
The cell with content:
```ruby
  '3-4
```
and format:
```ruby
  Custom: d-mmm
```
is incorrectly detected as a date.

Additional debug information:
```
$ puts raw_value
"41"
$ puts value
"3-4"
```

**Comment by weshatheleopard** [comment]
I do not understand your problem. What do you mean by "incorrectly detected as date"? Can you please provide a code sample?

P.S. Technically, `d-mmm` **is** a date format.

**Comment by caramdache** [comment]
The following code will output: `Date detected`.

```ruby
c.change_contents('3-4')
c.set_number_format('d-mmm')
if c.is_date?
  puts 'Date detected'
else
  puts 'Not a date'
end
```

The cell format is indeed a date format, but the cell value is a string (the string `"3-4"`) which is not a number. Hence the cell should not be detected as a date IMHO.

**Comment by weshatheleopard** [comment]
One of the changes done in the past year solved this one. Closing.
