### ISSUE TITLE
Hidden columns after change_column_font_name

### ISSUE THREAD

**Issue by rasaffie** [weshatheleopard/rubyXL#383]
There is a problem with [change_column_font_name](https://github.com/weshatheleopard/rubyXL/blob/a2836514a2662bd0632ac19b1502cb43aa638258/lib/rubyXL/convenience_methods/worksheet.rb#L512) on version 3.4.15. With code:
```ruby
workbook = RubyXL::Workbook.new()
sheet = workbook.worksheets[0]
headers = ['A', 'B', 'C']
headers.each_with_index do |header, index|
  sheet.add_cell(0, index, header)
  sheet.change_column_font_name(index, 'Calibri')
end
workbook.stream.string
```
columns end up hidden (the worksheet starts at column D) when I open it using _Excel_ version 16.42 on macOS 10.15.7. But if I use [change_row_font_name](https://github.com/weshatheleopard/rubyXL/blob/a2836514a2662bd0632ac19b1502cb43aa638258/lib/rubyXL/convenience_methods/worksheet.rb#L438) there is no problem.

EDIT: Might be related to https://github.com/weshatheleopard/rubyXL/issues/336

**Comment by svestu** [comment]
The problem still persists.
When I use worksheet.change_column_font_name(12, 'Arial'), Row 12 will be initially hidden.

**Comment by svestu** [comment]
It works! (y)  Thanks a lot :)
