### ISSUE TITLE
Return cell value with string formatter

### ISSUE THREAD

**Issue by patrickkulling** [weshatheleopard/rubyXL#387]
There are use cases where you want to use the StringFormatter for a cell, e.g. when the format of the cell is technically set to numeric/float, but the input is `20` (not `20.0`).

In these cases we would like to be able to avoid the mapping to ruby data types and return cell values as strings (in the above case `"20"`).

The POI library offers a method (and further customisation) for that.

see: [DataFormatter.formatCellValue(Cell cell)](https://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/DataFormatter.html)

Would it be possible to implement a similar behaviour to rubyXL?

**Comment by weshatheleopard** [comment]
I am not sure I am following. But, have you tried `cell.raw_value`? If I read correctly, that's what you want in this particular case.
