### ISSUE TITLE
TypeError: superclass mismatch for class File

### ISSUE THREAD

**Issue by wscourge** [weshatheleopard/rubyXL#388]
When used in Rails, I get the following error running the `rails server` command:

> TypeError: superclass mismatch for class File

This is a result of using the old version of [rubyzip gem](https://github.com/rubyzip/rubyzip). See [the gem's issue](https://github.com/rubyzip/rubyzip/issues/115) for reference.

This is the exact place where it mismatches the `File` superclass: _vendor/bundle/ruby/2.2.0/gems/rubyzip-1.2.3/lib/zip/file.rb:45_

Is there any chance you could upgrade to the latest rubyzip, where this is resolved (the `Zip::File` class is renamed)? Or is there a workaround for that?

**Comment by weshatheleopard** [comment]
Can you please see if the problem is solved? Current `rubzip` I'm using is 2.3.0.
