### ISSUE TITLE
How do I donate to this project?

### ISSUE THREAD

**Issue by gja** [weshatheleopard/rubyXL#400]
Been using this for a while, and would love to leave a tip.

We were trying to add a dropdown to our excel sheet, and was surprised that even this random requirement was in the readme.

Congrats on a job well done :-)

**Comment by weshatheleopard** [comment]
Thank you for your kind words.  Your sentiment is highly appreciated, but I doubt that any *monetary* contribution will hold any value for me (but will complicate my tax return) -- other than the aforementioned *sentimental* one -- and you already gave me *that one* with your comment =^.^=

I don't need money, thanks heavens. But what I direly and utterly need is time, a.k.a. *dedicated* contributors. I am working on this project pretty much alone, inbetween my work duties and real life, and I can only give so much time to it, which is obviously not enough: look at the bug list -- people want me to re-create Excel in Ruby! With all due respect, I can't do that, at least *single-handedily*.
