### ISSUE TITLE
Underline style corrupted

### ISSUE THREAD

**Issue by balgillo** [weshatheleopard/rubyXL#405]
RubyXL writes an invalid XLSX file if an underline style is present.  Any underline style gets written as `<u val="1"/>` to the stylesheet file `xl/styles.xml`.

This has two effects:

1. Double underline is converted to single underline
2. The `.xslx` file written is not valid OOXML and cannot be loaded by `openpyxl` (though Excel can still load it).

# Steps to reproduce

Using Excel, I created a new spreadsheet containing an underlined cell: [initial.xlsx](https://github.com/weshatheleopard/rubyXL/files/7568655/initial.xlsx) and another spreadsheet containing a double underlined cell: [double_underline.xlsx](https://github.com/weshatheleopard/rubyXL/files/7568818/double_underline.xlsx).  In the stylesheet file `xl/styles.xml` files I see `<font><u/>` for the single underline and `<font><u val="double"/>` for the double underline.  These load fine in `openpyxl`:

```
pip install openpyxl
python
import openpyxl
openpyxl.load_workbook("initial.xlsx") 
openpyxl.load_workbook("double_underline.xlsx") 
```
Then I load and save the files in RubyXL:
```
gem install rubyXL
irb
require 'rubyxl'
wb = RubyXL::Parser.parse("initial.xlsx")
wb.write("after_rubyxl_parse_write.xlsx")
wb = RubyXL::Parser.parse("double_underline.xlsx")
wb.write("dunder_after_rubyxl_parse_write.xlsx")
```
This creates [after_rubyxl_parse_write.xlsx](https://github.com/weshatheleopard/rubyXL/files/7568683/after_rubyxl_parse_write.xlsx) and [dunder_after_rubyxl_parse_write.xlsx](https://github.com/weshatheleopard/rubyXL/files/7568835/dunder_after_rubyxl_parse_write.xlsx).
 
In both output files, the stylesheet file `xl/styles.xml` contains `<u val="1"/>` in the `<font>` element.

[after_rubyxl_parse_write.xlsx](https://github.com/weshatheleopard/rubyXL/files/7568683/after_rubyxl_parse_write.xlsx) loads correctly in Excel, but [dunder_after_rubyxl_parse_write.xlsx](https://github.com/weshatheleopard/rubyXL/files/7568835/dunder_after_rubyxl_parse_write.xlsx) Sheet1!A1 now has a single underline instead of a double underline.

`openpyxl` chokes on both files:
```
openpyxl.load_workbook("after_rubyxl_parse_write.xlsx")
...(stack trace omitted)...

ValueError: Value must be one of {'singleAccounting', 'single', 'double', 'doubleAccounting'}
```

# Suggested fix

In [`font.rb`](https://github.com/weshatheleopard/rubyXL/blob/bc9742447a766716d37651a2e7bee6c643ab74b9/lib/rubyXL/objects/font.rb#L24), change the type of `font.u` from `RubyXL::BooleanValue` to `RubyXL::StringValue`, to match other enum fields e.g. `vertAlign`.

The valid `val` attribute values for the `<u>` element in stylesheets are `single`, `double`, `singleAccounting`, `doubleAccounting` and "none", according to [OpenXML docs](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.underlinevalues?view=openxml-2.8.1).  It seems that the `val` attribute can also be omitted, implying `single`.  RubyXL writes `<u val="1"/>` which is not valid.  Excel seems to tolerate this - it interprets it as single underline.

**Comment by weshatheleopard** [comment]
Good catch!

**Comment by balgillo** [comment]
This still isn't quite working.  It's now producing `<u val=""/>`, which is invalid according to 
[XSD](http://www.datypic.com/sc/ooxml/t-ssml_ST_UnderlineValues.html) and [openpyxl](https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1766#note_165979).

**Comment by balgillo** [comment]
I don't seem to be able to reopen this issue, but it is not fixed (see previous comment)
