### ISSUE TITLE
Consider removing Gemfile.lock, at least from the .files[] in gemspec

### ISSUE THREAD

**Issue by Nakilon** [weshatheleopard/rubyXL#407]
[It's a bad practice](https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/)

**Comment by laptopmutia** [comment]
https://github.com/weshatheleopard/rubyXL/commit/1b1abf61b006c681a70a4f5d01ac1a8adeb9fc0b fixed in here should be closed
