### ISSUE TITLE
undefined method change_content

### ISSUE THREAD

**Issue by chabgood** [weshatheleopard/rubyXL#414]
rubyXL (3.4.21)
I am getting this error in the rails console:

` worksheet[15][3].change_contents
Traceback (most recent call last):
        1: from (irb):9:in `evaluate'
NoMethodError (undefined method `change_contents' for #<RubyXL::Cell(15,3): "moo", datatype="str", style_index=27>)`

**Comment by weshatheleopard** [comment]
I recommend that you [read the documentation](https://github.com/weshatheleopard/rubyXL#label-Convenience+methods) prior to writing code.

**Comment by pvinis** [comment]
Could be nice to add a little error message to suggest adding these `require`s in the method_missing or something 🤔.

**Comment by weshatheleopard** [comment]
> Could be nice to add a little error message 

Could be nice to read the documentation? You cannot expect to just grab something off the internet and start using it without gaining any knowledge first.

**Comment by pvinis** [comment]
oof bro you're way too aggressive. Just gave a small suggestion. The rust compiler doesn't say RTFM, it gives hints.

Anyway whatever.

**Comment by weshatheleopard** [comment]
> The rust compiler doesn't say RTFM, it gives hints.

The C compiler did.
