### ISSUE TITLE
[Question] How to set the quotePrefix for the cell 

### ISSUE THREAD

**Issue by mikhailworkpath** [weshatheleopard/rubyXL#420]
Hey everyone, 
I have a question about the option `quotePrefix` to hide the quote in xlsx editors. I found this option here: https://github.com/weshatheleopard/rubyXL/blob/fb661a86dd312bd735bef88a6854951f2f5bed56/lib/rubyXL/objects/cell_style.rb#L44 
How can I apply this setting quotePrefix with a `true` value for a cell, I can not find an example or test for it. 
Thanks!

**Comment by weshatheleopard** [comment]
Judging by the fact that you are able to read the code, you are a software developer. _Figuring out how to do things_ is _the entire point_ of software developer's job. Asking questions "how to do it?" on the Internet is a helpful shortcut, yes, but github issue reporting tool is certainly not the place to do it; it is the place to report issues _with the product itself_, not issues with your _understanding_ of how to work with the product.

But, you made good first stride: you determined that the attribute you are looking for is on the `XF` object. Look around the code and see if you can find _other_ places that manipulate _other_ attributes of `XF` object and try writing your own code in a similar fashion.
