### ISSUE TITLE
Overflow: Clip ??

### ISSUE THREAD

**Issue by ddarbyson** [weshatheleopard/rubyXL#428]
Can someone please tell me how I would set a cell Overflow to `clip`

I can see in the code there is `ST_TextVertOverflowType`, but unsure how to define this as default for every cell.

**Comment by weshatheleopard** [comment]
It depends on what you are trying to do.

But generally you want something like this:

```
doc = RubyXL::Workbook.new
theme = doc.theme
theme.a_object_defaults.a_sp_def.a_body_pr.vert_overflow = 'clip'
```

For specicis if your task you need to read through the documentation of OOXML format.
