### ISSUE TITLE
Got a string with a part missing when i read value from cell.

### ISSUE THREAD

**Issue by Abson** [weshatheleopard/rubyXL#434]
![image](https://user-images.githubusercontent.com/13198014/216346164-c5cd727e-dd9f-4f2a-b085-e6f4e61aca1f.png)

When I parse the .xlsx file as above, I've got a string with a part missing => `Terms of use and privacy policy`. But the correct string is `<Terms of use and privacy policy>`

here is my code:

```ruby
 wb = RubyXL::Parser.parse(ExcelFile)
 wb[0]
 puts wb[0][649][2].value
```

**Comment by weshatheleopard** [comment]
Can you please attach the file you are having problems with?

**Comment by Abson** [comment]
> Can you please attach the file you are having problems with?

It's my fault, the xlsx cell has some string that has a formate problem that will make the xlsx
