### ISSUE TITLE
GitHub sponsor/open collective

### ISSUE THREAD

**Issue by harsh183** [weshatheleopard/rubyXL#440]
Hi @weshatheleopard ,

Thank you so much for all the activity and maintaining in the last few years. I first used this gem in 2017 and I still use it often. 

Would it be possible to set up any structure for us to donate? I tried looking on the readme and your GitHub profile and didn't find anything.

**Comment by weshatheleopard** [comment]
Yes and no.

Donating money? No, I will NEVER accept monetary donations. Given how _intractable_ IRS is, such donations (_especially_ in the amounts I can foresee people might be willing to offer) will be way more of a liability than benefit.

However, one thing that would be absolutely appreciated would be _donating brainpower_. Join me in working on this gem, write code, fix issues. One thing that is long overdue is creating a "streaming XML parser" and ditching `nokogiri`. The other one would be formula support. I have these on my mind -- but these would require _way_ more brainpower that I'm willing to dedicate to this project.

**Comment by harsh183** [comment]
That's understandable and thank you for responding. I think things are quite busy with work at the moment but I definitely do like taking a look around here or there.
