### ISSUE TITLE
Re-open #332

### ISSUE THREAD

**Issue by demogorgi** [weshatheleopard/rubyXL#446]
With [rubyxl_issue_332_example.xlsx](https://github.com/weshatheleopard/rubyXL/files/12700886/rubyxl_issue_332_example.xlsx)
```
require 'rubyXL'
path = "./rubyxl_issue_332_example.xlsx"
wb = RubyXL::Parser.parse(path)
wb.write(path)
wb = RubyXL::Parser.parse(path)
```
results in .../.gems/gems/rubyXL-3.4.17/lib/rubyXL/objects/ooxml_object.rb:152:in block in parse: undefined method href for nil:NilClass (NoMethodError)

**Comment by weshatheleopard** [comment]
Should be fixed in 3.4.32
