### ISSUE TITLE
undefined method `change_row_italics'

### ISSUE THREAD

**Issue by wbrisett** [weshatheleopard/rubyXL#447]
I tried to run an old script that used to work that uses rubyXL. I am now getting an undefined method error when I use the change_row routine. I did have:

`@worksheet.change_row_bold(0,true)`

When that failed, I changed it to match the docs of: 

`@worksheet.change_row_italics(0,true)`

That still threw the *Uncaught exception: undefined method `change_row_italics'*

I didn't have rubyXL installed on this particular device, so I had to install it. Has something changed that I'm not aware of here? 

version info: rubyXL (3.4.25)

**Comment by weshatheleopard** [comment]
You clearly missed [reading the documentation](https://github.com/weshatheleopard/rubyXL?tab=readme-ov-file#label-Convenience+methods).
