### ISSUE TITLE
when i parse a xlsx file, change_contents not found. and how can i change merged cell content?

### ISSUE THREAD

**Issue by Guoxweii** [weshatheleopard/rubyXL#449]
parse a xlsx file,and change some columns content, then raise a error

<img width="844" alt="image" src="https://github.com/weshatheleopard/rubyXL/assets/689550/d75e1fdd-1027-4057-8e5b-a18635fee8bc">

**Comment by weshatheleopard** [comment]
You should [read the documentation](https://github.com/weshatheleopard/rubyXL?tab=readme-ov-file#label-Convenience+methods).
