### ISSUE TITLE
`NoMethodError` when parsing certain .xlsx files

### ISSUE THREAD

**Issue by wakasa51** [weshatheleopard/rubyXL#463]
First of all, thank you for creating such a wonderful gem.

I’m currently encountering an issue where a NoMethodError is raised when trying to parse certain .xlsx files.
This error appears with files that were originally created as .numbers files on a Mac and then manually converted to .xlsx by simply changing the file extension.
We understand that files manually converted from .numbers to .xlsx are technically invalid, but sometimes our users attempt to use such files in our product.

**Steps to Reproduce:**

1. Attempt to parse a manually converted .xlsx file (for example, a .numbers file renamed to .xlsx) using the following code:
```ruby
File.open("./test.xlsx") { |f| RubyXL::Parser.parse_buffer(f.read) }
```
2. The following error occurs:
```ruby
NoMethodError: undefined method `root=' for nil:NilClass
from #{ruby_path}/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rubyXL-3.4.27/lib/rubyXL/objects/root.rb:68:in `parse_zip_file'
```

**Version:**
rubyXL version: `3.4.27`
Ruby version: `3.2.4`

**Expected Behavior:**

It would be greatly appreciated if, instead of a NoMethodError, the library could return a more descriptive error indicating that the parsing failed.

Thank you again for all your hard work on this gem!

**Comment by weshatheleopard** [comment]
Can you please provide a test file that exhibits this behavior?

**Comment by wakasa51** [comment]
Thank you for your prompt response!

I’ve attached a sample .xlsx file that exhibits the behavior described in the issue. 
[test.xlsx](https://github.com/user-attachments/files/16862983/test.xlsx)

Please let me know if there’s anything else I can provide or if you need further information.

Thank you again for your help!

**Comment by weshatheleopard** [comment]
The file that you provided is NOT an Open XML file. I have not seen anything like that before. Allegedly, it's produced by some sort of Mac spreadsheet program, with somebody just changing the extension to `.xlsx` by hand and hoping that would magically fix things. No it won't.

I really would rather not implement an entire format detector routine for a million different formats, with it's only purpose to say "hey human, this is not an Excel file, this is a EXE file / GIF file / PNG file / JPG file / etc." Garbage in, garbage out.
