### ISSUE TITLE
Warning when opening workbook written by rubyXL

### ISSUE THREAD

**Issue by sanfrecce-osaka** [weshatheleopard/rubyXL#464]
Change https://github.com/weshatheleopard/rubyXL/commit/cc86cb3ba7a2f25f5666cfb1028c2cff9c4b64af in [v3.4.32](https://github.com/weshatheleopard/rubyXL/releases/tag/v3.4.32) causes a warning when trying to open a workbook written by rubyXL.

The `app.xml` difference between [v3.4.31](https://github.com/weshatheleopard/rubyXL/releases/tag/v3.4.31) and [v3.4.32](https://github.com/weshatheleopard/rubyXL/releases/tag/v3.4.32) is below.

```diff
- <Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Company/><HeadingPairs><vt:vector baseType="variant" size="2"><vt:variant><vt:lpstr>Worksheets</vt:lpstr></vt:variant><vt:variant><vt:i4>1</vt:i4></vt:variant></vt:vector></HeadingPairs><TitlesOfParts><vt:vector baseType="lpstr" size="1"><vt:lpstr>Sheet1</vt:lpstr></vt:vector></TitlesOfParts><Application>Microsoft Macintosh Excel</Application><AppVersion>12.0000</AppVersion></Properties>
+ <Properties xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Company/><HeadingPairs><vt:vector baseType="variant" size="2"><vt:variant><vt:lpstr>Worksheets</vt:lpstr></vt:variant><vt:variant><vt:i4>1</vt:i4></vt:variant></vt:vector></HeadingPairs><TitlesOfParts><vt:vector baseType="lpstr" size="1"><vt:lpstr>Sheet1</vt:lpstr></vt:vector></TitlesOfParts><Application>Microsoft Macintosh Excel</Application><AppVersion>12.0000</AppVersion></Properties>
```

## Steps to reproduce the problem

Execute below.

```ruby
require 'rubyXL'
path = "./new_workbook.xlsx"
workbook = RubyXL::Workbook.new
workbook.write(path)
```

And open the workbook by Microsof Excel.

## Expected behavior

We open the file without warning.
Behavior up to [v3.4.31](https://github.com/weshatheleopard/rubyXL/releases/tag/v3.4.31) is this.

## Actual behavior

We open the file with below warning.

```
We found a problem with some content in 'new_workbook.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes.
```

## System configuration

- ruby: 3.3.6
- rubyXL: [v3.4.32](https://github.com/weshatheleopard/rubyXL/releases/tag/v3.4.32)
- Excel: Microsoft® Excel for Mac Version 16.89.1 (24091630)

**Comment by michaelwautier** [comment]
Thanks for raising this, I just encountered the same issue

**Comment by weshatheleopard** [comment]
Should be fixed now
