### ISSUE TITLE
Problems during unzipping on xls file parsing

### ISSUE THREAD

**Issue by HoneyryderChuck** [weshatheleopard/rubyXL#60]
I have a normal xls file i want to parse. So, I'm doing this:

``` ruby
RubyXL::Parser.parse "path/to/file.xls", skip_filename_check: true
```

And I get the following error :

Zip::ZipError: Zip end of central directory signature not found
        from /usr/local/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_central_directory.rb:97:in `get_e_o_c_d'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_central_directory.rb:55:in`read_e_o_c_d'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_central_directory.rb:85:in `read_from_str
        from /usr/local/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:67:in`block in initialize'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:66:in `open'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:66:in`initialize'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:87:in `new'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:87:in`open'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rubyXL-1.2.10/lib/rubyXL/zip.rb:10:in `unzip'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rubyXL-1.2.10/lib/rubyXL/parser.rb:326:in`decompress'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rubyXL-1.2.10/lib/rubyXL/parser.rb:47:in `parse'
        from (irb):4
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.2.11/lib/rails/comma
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.2.11/lib/rails/comma

Do you have an idea what it might be? The file doesn't seem corrupt, at least I can open it in microsoft excel.

**Comment by zaeem** [comment]
I am using this library to open .xlsx file and got the same error

**Comment by weshatheleopard** [comment]
@zaeem : I'm 99.9% sure your file is in `xls` format but with changed extension. If you want me to analyze it, upload it somewhere and give me the link.

You want to use https://github.com/zdavatz/spreadsheet for `.xls` files.

**Comment by shuargan** [comment]
Im having same prob, is there any mail where I can send you the file?

**Comment by weshatheleopard** [comment]
@shuargan: Here's an easy way for you to test on your own:

1. Change the extension of your `.xlsx` file to `.zip`
2. Try opening it in Windows like a `zip` file.
3. If it doesn't open, then it is `.xls` file, and not `.xlsx` file.

**Comment by shuargan** [comment]
Ok, thanks, im getting the error  OLE2 signature is invalid, try everything I found researching but nothing make it work.

**Comment by weshatheleopard** [comment]
@shuargan: In that case, it is NOT an Excel 2003+ file, it's an Excel 97 file, and this gem won't help you. You need the other gem:  https://github.com/zdavatz/spreadsheet

**Comment by shuargan** [comment]
Thanks, Ive just read this, but I started using spreadhseet and that one is the one who faile with ole2.

Thanks for everything

**Comment by weshatheleopard** [comment]
@shuargan: OK, you can upload your file somewhere (for example, https://mega.co.nz/) and give me the link so I can look at it. It's strange, it should be either one or the other.

**Comment by shuargan** [comment]
@weshatheleopard  https://mega.nz/#!bwAX1CqK

**Comment by weshatheleopard** [comment]
@shuargan you made that file private. I can't download it.

**Comment by shuargan** [comment]
@weshatheleopard its public, try with this one 
https://mega.nz/#!bwAX1CqK!5A1o4Ldl03nmZzJb1nX1P9YnQr0LylpULwqIoGMzJq8
key : !5A1o4Ldl03nmZzJb1nX1P9YnQr0LylpULwqIoGMzJq8

**Comment by weshatheleopard** [comment]
@shuargan: this is NOT an Excel file at all. It's an HTML file. Just open it with Notepad.

**Comment by shuargan** [comment]
@weshatheleopard  sorry men...

**Comment by computalya** [comment]
this happens when xlsx file is currently open by an another application(excel...)
